export const dynamic = "force-dynamic";
export const revalidate = 0;
export const fetchCache = "force-no-store";

import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { Document, Packer, Paragraph, HeadingLevel, Table, TableRow, TableCell, WidthType, TextRun } from "docx";
import * as XLSX from "xlsx";
import { jsPDF } from "jspdf";
import { networkTotal, distinctOfficialSites, type HydroModule } from "@/lib/network-registry";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const CFG:any = {
  pluviometrie:{table:"v_pluviometrie_dashboard_v47",date:"date_observation",value:"pluie_24h_mm",unit:"mm",label:"Suivi pluviométrique",cols:[["code_site","Station"],["nom_site","Localité"],["commune","Commune"],["date_observation","Date"],["pluie_24h_mm","Pluie 24 h (mm)"],["cumul_mensuel_mm","Cumul mensuel (mm)"],["observateur","Observateur"],["commentaire","Commentaire"],["latitude","Latitude"],["longitude","Longitude"]]},
  piezometrie:{table:"v_piezometrie_dashboard_v47",date:"date_observation",value:"niveau_statique",unit:"m",label:"Suivi piézométrique",cols:[["code_site","Piézomètre"],["nom_site","Localité"],["commune","Commune"],["date_observation","Date"],["niveau_statique","Niveau statique (m)"],["observateur","Observateur"],["commentaire","Commentaire"],["latitude","Latitude"],["longitude","Longitude"]]},
  limnimetrie:{table:"v_limnimetrie_dashboard_v47",date:"date_observation",value:"hauteur_eau",unit:"cm",label:"Suivi limnimétrique",cols:[["code_site","Station"],["nom_site","Localité / cours d'eau"],["commune","Commune"],["date_observation","Date"],["periode","Période"],["hauteur_eau","Hauteur d'eau (cm)"],["observateur","Observateur"],["commentaire","Commentaire"],["latitude","Latitude"],["longitude","Longitude"]]},
  points_eau:{table:"points_eau",date:"synced_at",value:null,unit:"",label:"Inventaire des points d'eau",cols:[["code_pe","Code"],["village","Village"],["commune","Commune"],["type_ouvrage","Type"],["etat","État"],["fonctionnalite_forage","Fonctionnalité"],["equipement_forage","Équipement"],["organe_gestion","Gestion"],["ph","pH"],["besoin_rehabilitation","Besoin réhabilitation"],["latitude","Latitude"],["longitude","Longitude"]]}
};

function periodStart(p:string){const d=new Date(),y=d.getUTCFullYear(),m=d.getUTCMonth();if(p==="mensuel")return new Date(Date.UTC(y,m,1)).toISOString();if(p==="trimestriel")return new Date(Date.UTC(y,Math.floor(m/3)*3,1)).toISOString();if(p==="annuel")return new Date(Date.UTC(y,0,1)).toISOString();return null}
function text(v:any){return String(v??"").trim()}
function num(v:any){if(v===null||v===undefined||v==="")return null;const n=Number(String(v).replace(",","."));return Number.isFinite(n)?n:null}
function clean(rows:any[],cols:any[]){return rows.map(r=>Object.fromEntries(cols.map(([k,l]:any)=>[l,r?.[k]??""])))}
function esc(v:any){return `"${String(v??"").replaceAll('"','""')}"`}
function csv(rows:any[]){if(!rows.length)return"Aucune donnée\n";const h=Object.keys(rows[0]);return[h.map(esc).join(";"),...rows.map(r=>h.map(k=>esc(r[k])).join(";"))].join("\n")}
function valueRows(rows:any[],key:string|null){return key?rows.map(r=>num(r[key])).filter((x):x is number=>x!==null):[]}
function byDate(rows:any[],cfg:any){const m=new Map<string,{sum:number,n:number}>();if(!cfg.value)return[];for(const r of rows){const d=text(r[cfg.date]).slice(0,10);const v=num(r[cfg.value]);if(!d||v===null)continue;const x=m.get(d)||{sum:0,n:0};x.sum+=v;x.n++;m.set(d,x)}return Array.from(m.entries()).sort(([a],[b])=>a.localeCompare(b)).map(([date,x])=>({date,value:x.sum/x.n})).slice(-30)}
function siteCounts(rows:any[]){const m=new Map<string,number>();for(const r of rows){const k=text(r.code_site||r.code_pe||r.code_station||r.code_piezo||"Non renseigné");m.set(k,(m.get(k)||0)+1)}return Array.from(m.entries()).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value).slice(0,12)}
function comments(rows:any[]){return rows.map(r=>text(r.commentaire||r.commentaire_mesure||r.commentaire_qualite||r.recommandation)).filter(Boolean).slice(0,12)}
function summary(rows:any[],module:string,cfg:any){const vals=valueRows(rows,cfg.value);const hydro=["pluviometrie","piezometrie","limnimetrie"].includes(module);const active=hydro?distinctOfficialSites(module as HydroModule,rows).size:new Set(rows.map(r=>text(r.code_pe)).filter(Boolean)).size;const total=hydro?networkTotal(module as HydroModule):active;return{enregistrements:rows.length,stations_reseau:total,stations_avec_donnees:active,couverture:total?Math.round(active/total*100):0,moyenne:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,min:vals.length?Math.min(...vals):null,max:vals.length?Math.max(...vals):null,latest:rows.map(r=>text(r[cfg.date]).slice(0,10)).filter(Boolean).sort().pop()||"—"}}
function narrative(module:string,s:any,cfg:any){const lines=[] as string[];lines.push(`${s.enregistrements} enregistrement(s) ont été retenus pour la période analysée.`);if(module!=="points_eau")lines.push(`${s.stations_avec_donnees} station(s) sur ${s.stations_reseau} disposent de données exploitables, soit une couverture de ${s.couverture} %.`);if(s.moyenne!==null)lines.push(`La valeur moyenne est de ${s.moyenne.toFixed(2)} ${cfg.unit}, avec un minimum de ${s.min} et un maximum de ${s.max}.`);lines.push(`Dernière donnée de la sélection : ${s.latest}.`);if(module==="piezometrie")lines.push("Interprétation : une augmentation de la profondeur du niveau statique correspond à une nappe plus profonde ; l'analyse de tendance doit être mise en relation avec la pluie, la saison et les prélèvements.");if(module==="pluviometrie")lines.push("Interprétation : les cumuls et la régularité des relevés doivent être examinés conjointement, notamment pour relier les épisodes pluvieux aux réponses hydriques.");if(module==="limnimetrie")lines.push("Interprétation : les variations rapides de hauteur doivent être vérifiées avec l'heure de lecture, les conditions météorologiques et l'état de la station.");return lines}

function hexToRgb(hex:string){const h=hex.replace("#","");return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)] as [number,number,number]}
const C={navy:"#0B2545",blue:"#0877B9",cyan:"#37B6D4",purple:"#58369A",green:"#1F9D63",orange:"#D97706",light:"#EEF5FB",gray:"#5F6F82",red:"#C2413A"};
function fill(pdf:jsPDF,color:string){pdf.setFillColor(...hexToRgb(color))}
function stroke(pdf:jsPDF,color:string){pdf.setDrawColor(...hexToRgb(color))}
function ink(pdf:jsPDF,color:string){pdf.setTextColor(...hexToRgb(color))}
function addBranding(pdf:jsPDF){try{const base=process.cwd();pdf.addImage(new Uint8Array(readFileSync(join(base,"public/logos/psore.png"))),"PNG",244,4,18,18);pdf.addImage(new Uint8Array(readFileSync(join(base,"public/logos/enabel.png"))),"PNG",264,5,12,12);pdf.addImage(new Uint8Array(readFileSync(join(base,"public/logos/dnh.png"))),"PNG",279,5,12,12)}catch{}}
function kpiCard(pdf:jsPDF,x:number,y:number,w:number,h:number,label:string,value:string,accent:string){fill(pdf,"#FFFFFF");stroke(pdf,"#D9E5EF");pdf.roundedRect(x,y,w,h,3,3,"FD");fill(pdf,accent);pdf.roundedRect(x,y,3,h,2,2,"F");ink(pdf,C.gray);pdf.setFontSize(7);pdf.text(label,x+7,y+7);ink(pdf,C.navy);pdf.setFontSize(15);pdf.setFont("helvetica","bold");pdf.text(value,x+7,y+18);pdf.setFont("helvetica","normal")}
function lineChart(pdf:jsPDF,series:any[],x:number,y:number,w:number,h:number,title:string,unit:string){ink(pdf,C.navy);pdf.setFontSize(10);pdf.setFont("helvetica","bold");pdf.text(title,x,y-3);pdf.setFont("helvetica","normal");stroke(pdf,"#C9D7E2");pdf.rect(x,y,w,h);if(series.length<2){ink(pdf,C.gray);pdf.setFontSize(8);pdf.text("Données temporelles insuffisantes",x+4,y+10);return}const vals=series.map(s=>s.value);const mn=Math.min(...vals),mx=Math.max(...vals),span=mx-mn||1;stroke(pdf,C.blue);pdf.setLineWidth(0.8);let prev:any=null;series.forEach((s,i)=>{const px=x+(i/(series.length-1))*w;const py=y+h-((s.value-mn)/span)*(h-8)-4;if(prev)pdf.line(prev[0],prev[1],px,py);fill(pdf,C.blue);pdf.circle(px,py,1,"F");prev=[px,py]});ink(pdf,C.gray);pdf.setFontSize(6);pdf.text(`${mn.toFixed(1)}–${mx.toFixed(1)} ${unit}`,x+3,y+h-2)}
function barChart(pdf:jsPDF,data:any[],x:number,y:number,w:number,h:number,title:string){ink(pdf,C.navy);pdf.setFontSize(10);pdf.setFont("helvetica","bold");pdf.text(title,x,y-3);pdf.setFont("helvetica","normal");const arr=data.slice(0,8);if(!arr.length){ink(pdf,C.gray);pdf.setFontSize(8);pdf.text("Aucune donnée",x+4,y+10);return}const mx=Math.max(...arr.map(d=>d.value),1);arr.forEach((d,i)=>{const yy=y+i*(h/arr.length);ink(pdf,C.gray);pdf.setFontSize(6);pdf.text(String(d.label).slice(0,16),x,yy+4);fill(pdf,C.cyan);pdf.roundedRect(x+28,yy+1,(w-38)*(d.value/mx),4,1,1,"F");ink(pdf,C.navy);pdf.text(String(d.value),x+w-8,yy+4)})}
function miniMap(pdf:jsPDF,rows:any[],x:number,y:number,w:number,h:number){ink(pdf,C.navy);pdf.setFontSize(10);pdf.setFont("helvetica","bold");pdf.text("Carte synthétique des sites",x,y-3);pdf.setFont("helvetica","normal");stroke(pdf,"#C9D7E2");fill(pdf,"#F7FAFC");pdf.rect(x,y,w,h,"FD");const pts=rows.map(r=>({lat:num(r.latitude),lon:num(r.longitude),label:text(r.code_site||r.code_pe)})).filter(p=>p.lat!==null&&p.lon!==null) as any[];if(!pts.length){ink(pdf,C.gray);pdf.setFontSize(8);pdf.text("Aucun point GPS exploitable",x+4,y+10);return}const lats=pts.map(p=>p.lat),lons=pts.map(p=>p.lon),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons),dy=maxLat-minLat||1,dx=maxLon-minLon||1;pts.slice(0,300).forEach(p=>{const px=x+4+(p.lon-minLon)/dx*(w-8);const py=y+h-4-(p.lat-minLat)/dy*(h-8);fill(pdf,C.purple);pdf.circle(px,py,1.2,"F")});ink(pdf,C.gray);pdf.setFontSize(6);pdf.text(`${pts.length} point(s) géolocalisé(s)`,x+3,y+h-2)}

export async function GET(req:NextRequest){
 const module=req.nextUrl.searchParams.get("module")||"points_eau";const format=req.nextUrl.searchParams.get("format")||"csv";const periode=req.nextUrl.searchParams.get("periode")||"personnalisee";const startCustom=req.nextUrl.searchParams.get("start");const endCustom=req.nextUrl.searchParams.get("end");const cfg=CFG[module]||CFG.points_eau;
 let q:any=supabaseAdmin.from(cfg.table).select("*").limit(20000);const start=startCustom||periodStart(periode);if(start)q=q.gte(cfg.date,start);if(endCustom)q=q.lte(cfg.date,endCustom);const{data,error}=await q;if(error)return NextResponse.json({ok:false,error:error.message},{status:500});
 const raw=data||[];const rows=clean(raw,cfg.cols);const s=summary(raw,module,cfg);const title=`PSORE — ${cfg.label}`;const periodLabel=startCustom||endCustom?`${startCustom||"début"} au ${endCustom||"présent"}`:periode;const analysis=narrative(module,s,cfg);const trend=byDate(raw,cfg);const sites=siteCounts(raw);const notes=comments(raw);
 if(format==="csv")return new Response(csv(rows),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="psore_${module}_${periode}.csv"`}});
 if(format==="xlsx"){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Indicateur:"Enregistrements",Valeur:s.enregistrements},{Indicateur:"Stations du réseau",Valeur:s.stations_reseau},{Indicateur:"Stations avec données",Valeur:s.stations_avec_donnees},{Indicateur:"Couverture (%)",Valeur:s.couverture},{Indicateur:"Moyenne",Valeur:s.moyenne??"—"},{Indicateur:"Minimum",Valeur:s.min??"—"},{Indicateur:"Maximum",Valeur:s.max??"—"},{Indicateur:"Dernière donnée",Valeur:s.latest}]),"Synthèse");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(analysis.map((x,i)=>({N:i+1,Observation:x}))),"Analyse");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(trend),"Evolution");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.length?rows:[{Message:"Aucune donnée"}]),"Détail des données");return new Response(XLSX.write(wb,{type:"array",bookType:"xlsx"}),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="psore_${module}_${periode}.xlsx"`}})}
 if(format==="docx"){const headers=rows.length?Object.keys(rows[0]):cfg.cols.map((x:any)=>x[1]);const headerCells=headers.map((h:string)=>new TableCell({children:[new Paragraph({children:[new TextRun({text:h,bold:true,color:"FFFFFF"})]})],shading:{fill:"0877B9"} as any}));const tableRows=[new TableRow({children:headerCells}),...rows.slice(0,1500).map(r=>new TableRow({children:headers.map(h=>new TableCell({children:[new Paragraph(String(r[h]??""))]}))}))];const summaryRows=[["Enregistrements",s.enregistrements],["Stations du réseau",s.stations_reseau],["Stations avec données",s.stations_avec_donnees],["Couverture",`${s.couverture}%`],["Moyenne",s.moyenne===null?"—":`${s.moyenne.toFixed(2)} ${cfg.unit}`],["Minimum",s.min??"—"],["Maximum",s.max??"—"],["Dernière donnée",s.latest]].map(([a,b])=>new TableRow({children:[new TableCell({children:[new Paragraph({children:[new TextRun({text:String(a),bold:true,color:"0B2545"})]})],shading:{fill:"EEF5FB"} as any}),new TableCell({children:[new Paragraph(String(b))]})]}));const children:any[]=[new Paragraph({children:[new TextRun({text:title,bold:true,color:"0B2545",size:34})]}),new Paragraph({children:[new TextRun({text:`Période : ${periodLabel}`,color:"5F6F82",size:20})]}),new Paragraph({text:"Résumé exécutif",heading:HeadingLevel.HEADING_1}),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:summaryRows}),new Paragraph({text:"Analyse et observations",heading:HeadingLevel.HEADING_1}),...analysis.map(x=>new Paragraph({text:`• ${x}`})),...(notes.length?[new Paragraph({text:"Commentaires terrain",heading:HeadingLevel.HEADING_2}),...notes.map(x=>new Paragraph({text:`• ${x}`}))]:[]),new Paragraph({text:"Détail des enregistrements",heading:HeadingLevel.HEADING_1}),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:tableRows})];const doc=new Document({sections:[{children}]});const b=await Packer.toBuffer(doc);return new Response(new Uint8Array(b),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","Content-Disposition":`attachment; filename="psore_${module}_${periode}.docx"`}})}
 if(format==="pdf"){const pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});fill(pdf,C.navy);pdf.rect(0,0,297,28,"F");ink(pdf,"#FFFFFF");pdf.setFont("helvetica","bold");pdf.setFontSize(19);pdf.text(title,14,12);pdf.setFont("helvetica","normal");pdf.setFontSize(8);pdf.text(`Rapport technique • ${periodLabel} • généré le ${new Date().toISOString().slice(0,10)}`,14,20);addBranding(pdf);kpiCard(pdf,14,34,48,24,"Enregistrements",String(s.enregistrements),C.blue);kpiCard(pdf,66,34,48,24,"Réseau physique",String(s.stations_reseau),C.purple);kpiCard(pdf,118,34,48,24,"Avec données",String(s.stations_avec_donnees),C.green);kpiCard(pdf,170,34,48,24,"Couverture",`${s.couverture}%`,C.cyan);kpiCard(pdf,222,34,61,24,"Moyenne",s.moyenne===null?"—":`${s.moyenne.toFixed(2)} ${cfg.unit}`,C.orange);lineChart(pdf,trend,14,70,126,45,"Évolution temporelle",cfg.unit);barChart(pdf,sites,154,70,129,45,"Volume de mesures par site");miniMap(pdf,raw,14,128,126,51);ink(pdf,C.navy);pdf.setFont("helvetica","bold");pdf.setFontSize(10);pdf.text("Lecture automatique et observations",154,125);pdf.setFont("helvetica","normal");ink(pdf,C.gray);pdf.setFontSize(7);let yy=132;for(const line of [...analysis,...notes.slice(0,4)]){const wrapped=pdf.splitTextToSize(`• ${line}`,125);pdf.text(wrapped,154,yy);yy+=wrapped.length*4+2;if(yy>178)break}ink(pdf,C.gray);pdf.setFontSize(6);pdf.text("PSORE — PTCS / Enabel / DNH-DRHK • Les interprétations automatiques sont des aides à la lecture et doivent être validées techniquement.",14,197);
 pdf.addPage("a4","landscape");fill(pdf,C.light);pdf.rect(0,0,297,20,"F");ink(pdf,C.navy);pdf.setFont("helvetica","bold");pdf.setFontSize(14);pdf.text("Détail des enregistrements",14,13);pdf.setFont("helvetica","normal");const hs=rows.length?Object.keys(rows[0]):[];let y=28;const widths=hs.map(()=>270/Math.max(hs.length,1));const drawHeader=()=>{fill(pdf,C.blue);pdf.rect(12,y-4,273,7,"F");ink(pdf,"#FFFFFF");pdf.setFont("helvetica","bold");pdf.setFontSize(5.5);hs.forEach((h,i)=>pdf.text(String(h).slice(0,22),13+widths.slice(0,i).reduce((a,b)=>a+b,0),y));pdf.setFont("helvetica","normal");y+=7};drawHeader();for(const r of rows.slice(0,2500)){if(y>195){pdf.addPage("a4","landscape");y=14;drawHeader()}if(Math.floor((y-35)/4)%2===0){fill(pdf,"#F7FAFC");pdf.rect(12,y-3,273,4,"F")}ink(pdf,C.navy);pdf.setFontSize(5.2);hs.forEach((h,i)=>pdf.text(String(r[h]??"").replace(/\s+/g," ").slice(0,28),13+widths.slice(0,i).reduce((a,b)=>a+b,0),y));y+=4}
 return new Response(pdf.output("arraybuffer"),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="psore_${module}_${periode}.pdf"`}})}
 return NextResponse.json({ok:false,error:"Format non supporté"},{status:400});
}
