export const dynamic="force-dynamic";export const revalidate=0;export const fetchCache="force-no-store";export const runtime="nodejs";
import{NextRequest,NextResponse}from"next/server";import{supabaseAdmin}from"@/lib/supabase-admin";import{Document,Packer,Paragraph,HeadingLevel,Table,TableRow,TableCell,WidthType,TextRun}from"docx";import*as XLSX from"xlsx";import{jsPDF}from"jspdf";import{networkTotal,distinctOfficialSites,displayStationCode,stationMetaByCode,type HydroModule}from"@/lib/network-registry";import{loadHydroRows,loadOfficialStations}from"@/lib/hydro-data";import{readFileSync}from"node:fs";import{join}from"node:path";import{requireApiRole}from"@/lib/auth-server";import{ROLE_DNH,ROLE_ADMIN,ROLE_SUPER_ADMIN}from"@/lib/permissions";
const CFG:any={pluviometrie:{tables:["v_pluviometrie_dashboard_v50","v_pluviometrie_dashboard_v47"],date:"date_observation",value:"pluie_24h_mm",unit:"mm",title:"PSORE — Rapport de suivi pluviométrique",cols:[["code_site","Code de la station"],["nom_site","Nom / localité"],["commune","Commune"],["date_observation","Date"],["pluie_24h_mm","Pluie 24 h (mm)"],["cumul_mensuel_mm","Cumul mensuel (mm)"],["observateur","Observateur"],["commentaire","Commentaire"],["latitude","Latitude"],["longitude","Longitude"]]},piezometrie:{tables:["v_piezometrie_dashboard_v50","v_piezometrie_dashboard_v47"],date:"date_observation",value:"niveau_statique",unit:"m",title:"PSORE — Rapport de suivi piézométrique",cols:[["code_site","Code de la station"],["nom_site","Nom / localité"],["commune","Commune"],["date_observation","Date"],["niveau_statique","Niveau statique (m)"],["observateur","Observateur"],["commentaire","Commentaire"],["latitude","Latitude"],["longitude","Longitude"]]},limnimetrie:{tables:["v_limnimetrie_dashboard_v50","v_limnimetrie_dashboard_v47"],date:"date_observation",value:"hauteur_eau",unit:"cm",title:"PSORE — Rapport de suivi limnimétrique",cols:[["code_site","Code de la station"],["nom_site","Nom / cours d'eau"],["commune","Commune"],["date_observation","Date"],["hauteur_eau","Hauteur d'eau (cm)"],["observateur","Observateur"],["commentaire","Commentaire"],["latitude","Latitude"],["longitude","Longitude"]]},points_eau:{tables:["points_eau"],date:"synced_at",value:null,unit:"",title:"PSORE — Rapport d'inventaire des points d'eau",cols:[["code_pe","Code"],["village","Village"],["commune","Commune"],["type_ouvrage","Type"],["etat","État"],["fonctionnalite_forage","Fonctionnalité"],["equipement_forage","Équipement"],["organe_gestion","Gestion"],["ph","pH"],["besoin_rehabilitation","Besoin réhabilitation"],["latitude","Latitude"],["longitude","Longitude"]]}};
const C={navy:"#0B2545",blue:"#0877B9",cyan:"#37B6D4",purple:"#58369A",orange:"#D97706",green:"#1F9D63",red:"#C2413A",light:"#EEF5FB",gray:"#5F6F82"};
function text(v:any){const s=String(v??"").trim();return s||"Non renseigné"}function rawText(v:any){return String(v??"").trim()}function num(v:any){if(v===null||v===undefined||v==="")return null;const n=Number(String(v).replace(",","."));return Number.isFinite(n)?n:null}function fr(v:any,d=2){const n=num(v);return n===null?"Non renseigné":n.toLocaleString("fr-FR",{minimumFractionDigits:0,maximumFractionDigits:d})}function escCsv(v:any){return`"${String(v??"Non renseigné").replace(/"/g,'""')}"`}function periodStart(p:string){const d=new Date(),y=d.getUTCFullYear(),m=d.getUTCMonth();if(p==="mensuel")return new Date(Date.UTC(y,m,1)).toISOString().slice(0,10);if(p==="trimestriel")return new Date(Date.UTC(y,Math.floor(m/3)*3,1)).toISOString().slice(0,10);if(p==="annuel")return`${y}-01-01`;return""}function dateOk(v:any){return/^\d{4}-\d{2}-\d{2}/.test(rawText(v))}function validGps(r:any){const la=num(r.latitude),lo=num(r.longitude);return la!==null&&lo!==null&&la>=-90&&la<=90&&lo>=-180&&lo<=180}
async function selectRows(tables:string[],start:string,end:string,dateKey:string){let last="";for(let i=0;i<tables.length;i++){let q:any=supabaseAdmin.from(tables[i]).select("*").limit(20000);if(start)q=q.gte(dateKey,start);if(end)q=q.lte(dateKey,end);const r=await q;if(!r.error)return r.data||[];last=r.error.message}throw new Error(last||"Source indisponible")}
async function selectModuleRows(module:string,start:string,end:string,cfg:any){if(hydro(module)){const loaded=await loadHydroRows(module as HydroModule);let rows=loaded.rows;if(start)rows=rows.filter((r:any)=>rawText(r[cfg.date]).slice(0,10)>=start);if(end)rows=rows.filter((r:any)=>rawText(r[cfg.date]).slice(0,10)<=end);return{rows,rejected:loaded.rejected||0,source:loaded.source,historicalCount:loaded.historicalRows?.length||0,futureCount:loaded.futureRows?.length||0,cutoff:loaded.cutoff||""}}return{rows:await selectRows(cfg.tables,start,end,cfg.date),rejected:0,source:"Supabase",historicalCount:0,futureCount:0,cutoff:""}}
async function networkMapRows(module:string,observed:any[]){if(!hydro(module))return observed;const stationRows=await loadOfficialStations(module as HydroModule);const obsQuality=quality(observed,module,CFG[module]);return stationRows.map((x:any)=>{const code=rawText(x.code_site||x.code_station||x.code_piezo),matches=obsQuality.filter((o:any)=>rawText(o.code_site).toUpperCase()===code.toUpperCase()),status=!matches.length?"Sans donnée":matches.some((o:any)=>o.__status!=="Validé")?"À vérifier":"Validé",cum=module==="pluviometrie"?matches.map((o:any)=>num(o.pluie_24h_mm)).filter((v:any)=>v!==null).reduce((a:number,b:number)=>a+b,0):0;return{...x,code_site:code,nom_site:x.nom_site||x.village||x.localite||x.cours_eau||code,__status:status,__cum:cum}})}
function iqrBounds(rows:any[],key:string){const xs=rows.map(r=>num(r[key])).filter((x):x is number=>x!==null).sort((a,b)=>a-b);if(xs.length<4)return null;const q=(p:number)=>xs[Math.min(xs.length-1,Math.floor((xs.length-1)*p))];const q1=q(.25),q3=q(.75),iqr=q3-q1;return{low:q1-1.5*iqr,high:q3+1.5*iqr}}
function quality(rows:any[],module:string,cfg:any){const b=cfg.value?iqrBounds(rows,cfg.value):null,counts=new Map<string,number>();for(let i=0;i<rows.length;i++){const r=rows[i],code=rawText(r.code_site||r.code_pe||r.code_station||r.code_piezo),date=rawText(r[cfg.date]).slice(0,10),v=cfg.value?num(r[cfg.value]):null,key=`${code}|${date}|${v===null?"":v}`;counts.set(key,(counts.get(key)||0)+1)}return rows.map((r:any)=>{const code=rawText(r.code_site||r.code_pe||r.code_station||r.code_piezo),date=rawText(r[cfg.date]).slice(0,10),v=cfg.value?num(r[cfg.value]):null,key=`${code}|${date}|${v===null?"":v}`,duplicate=(counts.get(key)||0)>1,missing=!code||!dateOk(date)||(cfg.value&&v===null),gpsBad=!validGps(r),ph=num(r.ph),pointPhImpossible=module==="points_eau"&&ph!==null&&(ph<0||ph>14),atypical=!!(pointPhImpossible||(b&&v!==null&&(v<b.low||v>b.high)));let status="Validé";if(duplicate)status="Doublon potentiel";else if(missing)status="Donnée incomplète";else if(gpsBad||atypical)status="À vérifier";return{...r,__status:status,__atypical:atypical,__gpsBad:gpsBad,__duplicate:duplicate,__phImpossible:pointPhImpossible}})}
function hydro(module:string){return["pluviometrie","piezometrie","limnimetrie"].includes(module)}function stats(rows:any[],module:string,cfg:any){const vals=cfg.value?rows.map(r=>num(r[cfg.value])).filter((x):x is number=>x!==null):[],stations=hydro(module)?distinctOfficialSites(module as HydroModule,rows).size:new Set(rows.map(r=>rawText(r.code_pe)).filter(Boolean)).size,total=hydro(module)?networkTotal(module as HydroModule):stations;return{n:rows.length,total,stations,cov:total?stations/total*100:0,avg:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,min:vals.length?Math.min.apply(null,vals):null,max:vals.length?Math.max.apply(null,vals):null,last:rows.map(r=>rawText(r[cfg.date]).slice(0,10)).filter(Boolean).sort().pop()||"Non renseigné"}}
function stationLabel(module:string,r:any){if(!hydro(module))return rawText(r.code_pe)||"Non renseigné";const meta=stationMetaByCode(module as HydroModule,r.code_site||r.code_station||r.code_piezo);return meta?displayStationCode(module as HydroModule,meta.code):"Non exploitable — station non identifiée"}
function monthKey(d:string){return d.slice(0,7)}function cumulativePluvio(rows:any[]){const m=new Map<string,number>();const out:any[]=[];const sorted=rows.slice().sort((a,b)=>rawText(a.date_observation).localeCompare(rawText(b.date_observation)));for(let i=0;i<sorted.length;i++){const r=sorted[i],code=stationLabel("pluviometrie",r),d=rawText(r.date_observation).slice(0,10),v=num(r.pluie_24h_mm);if(!d||v===null)continue;const key=`${code}|${monthKey(d)}`,cum=(m.get(key)||0)+v;m.set(key,cum);out.push({code,date:d,value:v,cum})}return out}
function reportRows(rows:any[],module:string,cfg:any){const q=quality(rows,module,cfg),plCum=module==="pluviometrie"?cumulativePluvio(q):[],cumMap=new Map(plCum.map(x=>[`${x.code}|${x.date}`,x.cum]));return q.map(r=>{const o:any={};for(let i=0;i<cfg.cols.length;i++){const k=cfg.cols[i][0],label=cfg.cols[i][1];let v=r[k];if(k==="code_site")v=stationLabel(module,r);if(v===null||v===undefined||v==="")v="Non renseigné";o[label]=v}if(module==="pluviometrie")o["Cumul calculé station/mois (mm)"]=cumMap.get(`${stationLabel(module,r)}|${rawText(r.date_observation).slice(0,10)}`)??"Non renseigné";o["Statut du contrôle"]=r.__status;return o})}
function qaSummary(rows:any[]){return{verifier:rows.filter(r=>r.__status==="À vérifier").length,incomplets:rows.filter(r=>r.__status==="Donnée incomplète").length,doublons:rows.filter(r=>r.__status==="Doublon potentiel").length,atypiques:rows.filter(r=>r.__atypical).length,gps:rows.filter(r=>r.__gpsBad).length}}
function analysis(rows:any[],module:string,cfg:any,s:any,startDate="",endDate=""){const q=quality(rows,module,cfg),qa=qaSummary(q),lines:string[]=[];lines.push(`Résultats confirmés : ${s.n} observation(s) retenue(s) sur la période analysée.`);if(hydro(module))lines.push(`Couverture du réseau : ${s.stations} station(s) avec données sur ${s.total}, soit ${fr(s.cov,1)} %.`);if(s.avg!==null)lines.push(`Moyenne des valeurs valides${s.stations>1?" (toutes stations confondues)":""} : ${fr(s.avg)} ${cfg.unit}. Minimum : ${fr(s.min)} ${cfg.unit}; maximum : ${fr(s.max)} ${cfg.unit}.`);if(cfg.value&&q.length){const valid=q.filter(r=>num(r[cfg.value])!==null);if(valid.length){const lo=valid.reduce((a,b)=>Number(a[cfg.value])<=Number(b[cfg.value])?a:b),hi=valid.reduce((a,b)=>Number(a[cfg.value])>=Number(b[cfg.value])?a:b);lines.push(`Valeur la plus faible : ${fr(lo[cfg.value])} ${cfg.unit} à ${stationLabel(module,lo)} (${rawText(lo[cfg.date]).slice(0,10)||"date non renseignée"}). Valeur la plus forte : ${fr(hi[cfg.value])} ${cfg.unit} à ${stationLabel(module,hi)} (${rawText(hi[cfg.date]).slice(0,10)||"date non renseignée"}).`)}}lines.push(`Dernière observation retenue : ${s.last}.`);if(startDate&&endDate){const a=new Date(startDate+"T00:00:00Z"),b=new Date(endDate+"T00:00:00Z");const days=Math.round((b.getTime()-a.getTime())/86400000)+1;if(days>0&&days<=120){const have=new Set(q.map(r=>rawText(r[cfg.date]).slice(0,10)).filter(Boolean)),miss:string[]=[];for(let d=new Date(a);d<=b;d=new Date(d.getTime()+86400000)){const k=d.toISOString().slice(0,10);if(!have.has(k))miss.push(k)}if(miss.length)lines.push(`Périodes sans observation : ${miss.length} jour(s) sans donnée dans la sélection${miss.length<=8?` (${miss.join(", ")})`:""}.`)}}if(qa.atypiques)lines.push(`Anomalies potentielles : ${qa.atypiques} valeur(s) atypique(s) détectée(s) statistiquement et nécessitant une vérification; aucune n'a été supprimée.`);if(qa.gps)lines.push(`Coordonnées : ${qa.gps} observation(s)/station(s) présentent des coordonnées absentes ou invalides.`);if(qa.incomplets)lines.push(`Données manquantes : ${qa.incomplets} ligne(s) incomplète(s).`);if(qa.doublons)lines.push(`Doublons potentiels : ${qa.doublons} ligne(s) partagent le même code, la même date et la même valeur.`);if(!qa.atypiques&&!qa.gps&&!qa.incomplets&&!qa.doublons)lines.push("Contrôle automatique : aucune anomalie potentielle détectée selon les règles appliquées.");return{lines,qa}}
function csv(rows:any[]){if(!rows.length)return"Aucune donnée\n";const h=Object.keys(rows[0]);return[h.map(escCsv).join(";"),...rows.map(r=>h.map(k=>escCsv(r[k])).join(";"))].join("\n")}
function rgb(hex:string){const h=hex.replace("#","");return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]as[number,number,number]}function ink(p:jsPDF,c:string){p.setTextColor(...rgb(c))}function fill(p:jsPDF,c:string){p.setFillColor(...rgb(c))}function stroke(p:jsPDF,c:string){p.setDrawColor(...rgb(c))}function brand(p:jsPDF){try{const b=process.cwd();p.addImage(new Uint8Array(readFileSync(join(b,"public/logos/psore.png"))),"PNG",246,4,17,17);p.addImage(new Uint8Array(readFileSync(join(b,"public/logos/enabel.png"))),"PNG",266,5,11,11);p.addImage(new Uint8Array(readFileSync(join(b,"public/logos/dnh.png"))),"PNG",281,5,10,10)}catch{}}
function card(p:jsPDF,x:number,y:number,w:number,label:string,value:string,c:string){fill(p,"#FFFFFF");stroke(p,"#D9E5EF");p.roundedRect(x,y,w,21,3,3,"FD");fill(p,c);p.roundedRect(x,y,3,21,2,2,"F");ink(p,C.gray);p.setFontSize(6.5);p.text(label,x+6,y+6);ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(13);p.text(value,x+6,y+16);p.setFont("helvetica","normal")}
function seriesByStation(rows:any[],module:string,cfg:any){const map=new Map<string,any[]>();for(let i=0;i<rows.length;i++){const r=rows[i],v=cfg.value?num(r[cfg.value]):null,d=rawText(r[cfg.date]).slice(0,10);if(v===null||!d)continue;const k=stationLabel(module,r);const a=map.get(k)||[];a.push({date:d,value:v});map.set(k,a)}return Array.from(map.entries()).slice(0,10).map(([label,values])=>({label,values:values.sort((a,b)=>a.date.localeCompare(b.date))}))}
const PALETTE=[C.purple,C.blue,C.orange,C.green,"#DC2626","#0F766E","#9333EA","#EA580C","#0284C7","#64748B"];
function drawChart(p:jsPDF,rows:any[],module:string,cfg:any,x:number,y:number,w:number,h:number){ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(9);p.text(module==="pluviometrie"?"Évolution des précipitations":"Évolution des mesures",x,y-3);p.setFont("helvetica","normal");const s=seriesByStation(rows,module,cfg);if(!s.length){ink(p,C.gray);p.setFontSize(7);p.text("Aucune donnée disponible",x+4,y+9);return}let all:number[]=[];s.forEach(a=>a.values.forEach(v=>all.push(v.value)));const max=Math.max.apply(null,all.concat([1])),dates=Array.from(new Set(s.reduce((a:any[],z:any)=>a.concat(z.values.map((v:any)=>v.date)),[]))).sort().slice(-24);stroke(p,"#D8E2EC");p.rect(x,y,w,h);for(let g=0;g<=4;g++){stroke(p,"#E9EFF5");const gy=y+h-g*h/4;p.line(x,gy,x+w,gy);ink(p,C.gray);p.setFontSize(5.5);p.text(fr(max*g/4,1),x-10,gy+1)}const groupW=w/Math.max(1,dates.length),barW=Math.max(.6,groupW/Math.max(1,s.length)*.75);for(let i=0;i<dates.length;i++){for(let j=0;j<s.length;j++){const found=s[j].values.find((v:any)=>v.date===dates[i]);if(!found)continue;const bh=(found.value/max)*(h-6);fill(p,PALETTE[j%PALETTE.length]);p.rect(x+i*groupW+j*barW,y+h-bh,barW-.2,bh,"F")}}if(module==="pluviometrie"){const cumSeries=s.map(z=>{let c=0;return{label:z.label,values:z.values.map((v:any)=>{c+=v.value;return{date:v.date,value:c}})}});const allCum:number[]=[];cumSeries.forEach(z=>z.values.forEach((v:any)=>allCum.push(v.value)));const maxCum=Math.max.apply(null,allCum.concat([1]));for(let j=0;j<cumSeries.length;j++){stroke(p,PALETTE[j%PALETTE.length]);p.setLineWidth(.5);let prev:any=null;for(let i=0;i<dates.length;i++){const found=cumSeries[j].values.find((v:any)=>v.date===dates[i]);if(!found)continue;const px=x+i*groupW+groupW/2,py=y+h-(found.value/maxCum)*(h-6);if(prev)p.line(prev[0],prev[1],px,py);prev=[px,py]}}ink(p,C.gray);p.setFontSize(5);p.text(`Cumul max : ${fr(maxCum,1)} mm`,x+w-34,y+h-1)}ink(p,C.gray);p.setFontSize(5);if(dates.length){p.text(dates[0],x,y+h+4);p.text(dates[dates.length-1],x+w-18,y+h+4)}let ly=y+4;for(let i=0;i<s.length;i++){fill(p,PALETTE[i%PALETTE.length]);p.rect(x+w-40,ly-2,3,2,"F");ink(p,C.navy);p.setFontSize(5);p.text(s[i].label.slice(0,22),x+w-36,ly);ly+=3.4;if(ly>y+h-2)break}}
async function osmMap(p:jsPDF,rows:any[],module:string,x:number,y:number,w:number,h:number){
  ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(9);p.text("Localisation des stations et disponibilité des données",x,y-3);p.setFont("helvetica","normal");
  const cumByStation=new Map<string,number>();if(module==="pluviometrie")for(const r of rows){const k=stationLabel(module,r),v=num(r.pluie_24h_mm);if(v!==null)cumByStation.set(k,(cumByStation.get(k)||0)+v)}
  const unique=new Map<string,any>();for(const r of rows){if(!validGps(r))continue;const label=stationLabel(module,r);if(label.startsWith("Non exploitable"))continue;if(!unique.has(label))unique.set(label,{lat:Number(r.latitude),lon:Number(r.longitude),label,status:r.__status||"Validé",cum:num(r.__cum)??cumByStation.get(label)??0})}
  const pts=Array.from(unique.values());fill(p,"#F7FAFC");stroke(p,"#C9D7E2");p.rect(x,y,w,h,"FD");if(!pts.length){ink(p,C.gray);p.setFontSize(7);p.text("Aucune station officielle avec coordonnées valides",x+4,y+9);return}
  let minLat=Math.min(...pts.map(z=>z.lat)),maxLat=Math.max(...pts.map(z=>z.lat)),minLon=Math.min(...pts.map(z=>z.lon)),maxLon=Math.max(...pts.map(z=>z.lon));const latPad=Math.max(.01,(maxLat-minLat)*.18),lonPad=Math.max(.01,(maxLon-minLon)*.18);minLat-=latPad;maxLat+=latPad;minLon-=lonPad;maxLon+=lonPad;
  const span=Math.max(maxLon-minLon,(maxLat-minLat)*1.3);const z=Math.max(7,Math.min(13,Math.floor(Math.log2(360/Math.max(span,.01)))-1)),n2=Math.pow(2,z);
  const tileX=(lo:number)=>(lo+180)/360*n2;const tileY=(la:number)=>(1-Math.log(Math.tan(la*Math.PI/180)+1/Math.cos(la*Math.PI/180))/Math.PI)/2*n2;
  const fx0=tileX(minLon),fx1=tileX(maxLon),fy0=tileY(maxLat),fy1=tileY(minLat);const tx0=Math.floor(fx0),tx1=Math.floor(fx1),ty0=Math.floor(fy0),ty1=Math.floor(fy1);let bg=true;
  const sx=w/Math.max(.001,fx1-fx0),sy=h/Math.max(.001,fy1-fy0);for(let tx=tx0;tx<=tx1;tx++)for(let ty=ty0;ty<=ty1;ty++){if((tx1-tx0+1)*(ty1-ty0+1)>16){bg=false;break}try{const rr=await fetch(`https://tile.openstreetmap.org/${z}/${tx}/${ty}.png`,{headers:{"User-Agent":"PSORE-PTCS/5.1 technical-report"}});if(!rr.ok)throw new Error("tile");const ab=await rr.arrayBuffer();const px=x+(tx-fx0)*sx,py=y+(ty-fy0)*sy;p.addImage(new Uint8Array(ab),"PNG",px,py,sx,sy)}catch{bg=false}}
  const project=(la:number,lo:number)=>[x+(tileX(lo)-fx0)*sx,y+(tileY(la)-fy0)*sy];const maxCum=Math.max(...pts.map(z=>z.cum),1);const labelBoxes:any[]=[];
  for(const pt of pts){const q=project(pt.lat,pt.lon),c=pt.status==="Validé"?C.purple:pt.status==="À vérifier"?C.red:C.gray,radius=module==="pluviometrie"?1.15+1.4*Math.sqrt((pt.cum||0)/maxCum):module==="points_eau"?.75:1.45;fill(p,c);stroke(p,"#FFFFFF");p.circle(q[0],q[1],radius,"FD");if(module==="points_eau"&&pts.length>50)continue;let lx=q[0]+1.8,ly=q[1]-.8;const label=pt.label.slice(0,28);for(const b of labelBoxes){if(Math.abs(lx-b.x)<18&&Math.abs(ly-b.y)<4){ly+=4}}labelBoxes.push({x:lx,y:ly});fill(p,"#FFFFFF");p.setFillColor(255,255,255);ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(4.4);p.text(label,lx,ly);p.setFont("helvetica","normal")}
  ink(p,C.navy);p.setFontSize(7);p.text("N",x+w-8,y+7);p.line(x+w-6,y+9,x+w-6,y+18);p.line(x+w-6,y+9,x+w-8,y+13);p.line(x+w-6,y+9,x+w-4,y+13);p.setLineWidth(1);p.line(x+5,y+h-7,x+25,y+h-7);p.setLineWidth(.2);ink(p,C.gray);p.setFontSize(5.2);p.text(bg?"Fond © contributeurs OpenStreetMap":"Fond OSM partiellement indisponible lors de la génération",x+4,y+h-2);if(module==="points_eau"&&pts.length>50){ink(p,C.gray);p.setFontSize(4.8);p.text("Codes des points d’eau : voir tableau détaillé (étiquettes masquées pour lisibilité).",x+4,y+h-7)}fill(p,C.purple);p.circle(x+72,y+h-3,1.3,"F");ink(p,C.gray);p.text("données validées",x+75,y+h-2);fill(p,C.gray);p.circle(x+102,y+h-3,1.3,"F");p.text("sans donnée",x+105,y+h-2);fill(p,C.red);p.circle(x+126,y+h-3,1.3,"F");p.text("à vérifier",x+129,y+h-2)
}
function addFooter(p:jsPDF,source:string){const pages=p.getNumberOfPages();for(let i=1;i<=pages;i++){p.setPage(i);ink(p,C.gray);p.setFontSize(5.5);p.text(`PSORE • PTCS – Enabel – DNH/DRHK • Sources : ${source} • Production : ${new Date().toISOString().slice(0,10)}`,12,204);p.text(`Page ${i}/${pages}`,276,204)}}
function restorationTechnology(pr:any){
  const flags:[string,string][]=[["Demi-lune","Demi-lune"],["Cordon pie","Cordon pierreux"],["Zaï","Zaï"],["ZaÃ¯","Zaï"],["RNA","RNA"],["Digue filt","Digue filtrante"],["Compostage","Compostage"],["Reboisemen","Reboisement"],["Enrichisse","Enrichissement"],["Mise en d","Mise en défens"],["Aménageme","Aménagement"]];
  const hits:string[]=[];for(const[k,label]of flags){const key=Object.keys(pr||{}).find(x=>x.startsWith(k));if(key&&String(pr[key]??"").trim()!==""&&!/^(0|non|false)$/i.test(String(pr[key]).trim()))hits.push(label)}
  const method=rawText(pr?.["Méthode d"]||pr?.["MÃ©thode d"]||pr?.["Mï¿½thode d"]);if(method&&!hits.includes(method))hits.unshift(method);
  return hits.length?hits.join(" + "):"Non renseigné";
}
function restorationCommune(pr:any){return rawText(pr?.commune_2||pr?.Commune||pr?.commune)||"Non renseignée"}
function geoRings(g:any){if(!g)return[];if(g.type==="Polygon")return[g.coordinates?.[0]||[]];if(g.type==="MultiPolygon")return(g.coordinates||[]).map((p:any)=>p?.[0]||[]);return[]}
function drawSubBasinExcerpt(p:jsPDF,d:any,x:number,y:number,w:number,h:number){
  ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(9);p.text(`Extrait cartographique — SB-${d.id}`,x,y-3);p.setFont("helvetica","normal");fill(p,"#F7FAFC");stroke(p,"#C9D7E2");p.rect(x,y,w,h,"FD");
  const rings=geoRings(d.feature?.geometry);const all=rings.reduce((a:any[],r:any[])=>a.concat(r),[]);if(!all.length){ink(p,C.gray);p.setFontSize(7);p.text("Géométrie indisponible",x+4,y+9);return}
  const xs=all.map((q:any)=>Number(q[0])),ys=all.map((q:any)=>Number(q[1])),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=.06,dx=(maxX-minX)||1,dy=(maxY-minY)||1;
  const project=(lon:number,lat:number)=>[x+4+(lon-(minX-dx*pad))/(dx*(1+2*pad))*(w-8),y+h-4-(lat-(minY-dy*pad))/(dy*(1+2*pad))*(h-8)];
  fill(p,"#E6F2FA");stroke(p,C.blue);p.setLineWidth(.7);for(const ring of rings){const pts=ring.map((q:any)=>project(Number(q[0]),Number(q[1])));if(pts.length>2){for(let i=1;i<pts.length;i++)p.line(pts[i-1][0],pts[i-1][1],pts[i][0],pts[i][1])}}
  for(const r of d.restorations||[]){const c=r.centroid;if(!c)continue;const q=project(c[0],c[1]);fill(p,C.orange);stroke(p,"#FFFFFF");p.circle(q[0],q[1],1.1,"FD")}
  for(const m of ["pluviometrie","piezometrie","limnimetrie"]){const color=m==="pluviometrie"?C.purple:m==="piezometrie"?C.cyan:C.green;for(const r of d.modules?.[m]||[]){if(!validGps(r))continue;const q=project(Number(r.longitude),Number(r.latitude));fill(p,color);stroke(p,"#FFFFFF");p.circle(q[0],q[1],1.5,"FD");ink(p,C.navy);p.setFontSize(4.2);p.text(stationLabel(m,r).slice(0,24),q[0]+1.8,q[1]+.5)}}
  ink(p,C.gray);p.setFontSize(5);p.text("Contour SB",x+4,y+h-2);fill(p,C.orange);p.circle(x+26,y+h-3,1,"F");p.text("restauration",x+29,y+h-2);fill(p,C.purple);p.circle(x+51,y+h-3,1,"F");p.text("pluie",x+54,y+h-2);fill(p,C.cyan);p.circle(x+66,y+h-3,1,"F");p.text("PZ",x+69,y+h-2);fill(p,C.green);p.circle(x+77,y+h-3,1,"F");p.text("limni",x+80,y+h-2)
}
async function subBasinData(sbId:string){
  const sb:any=JSON.parse(readFileSync(join(process.cwd(),"public/data/decisionnel/sous_bassins_data.json"),"utf8")),rest:any=JSON.parse(readFileSync(join(process.cwd(),"public/data/decisionnel/restaurations_data.json"),"utf8"));
  const feature=(sb.features||[]).find((f:any)=>String(f?.properties?.HydroID??f?.properties?.OBJECTID)===String(sbId));if(!feature)throw new Error(`Sous-bassin SB-${sbId} introuvable`);
  const ring=(pt:any,r:any[])=>{let c=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const a=r[i],b=r[j];if(((a[1]>pt[1])!==(b[1]>pt[1]))&&(pt[0]<(b[0]-a[0])*(pt[1]-a[1])/(b[1]-a[1]||1e-12)+a[0]))c=!c}return c};
  const inside=(pt:any,g:any)=>{if(!pt||!g)return false;if(g.type==="Polygon")return ring(pt,g.coordinates[0]||[]);if(g.type==="MultiPolygon")return(g.coordinates||[]).some((poly:any)=>ring(pt,poly[0]||[]));return false};
  const cent=(g:any)=>{const pts:any[]=[];const walk=(x:any)=>{if(Array.isArray(x)&&typeof x[0]==="number")pts.push(x);else if(Array.isArray(x))x.forEach(walk)};walk(g?.coordinates);return pts.length?[pts.reduce((sum:number,point:any)=>sum+point[0],0)/pts.length,pts.reduce((sum:number,point:any)=>sum+point[1],0)/pts.length]:null};
  const restorRaw=(rest.features||[]).filter((r:any)=>inside(cent(r.geometry),feature.geometry));
  const restorations=restorRaw.map((r:any)=>({properties:r.properties||{},geometry:r.geometry,centroid:cent(r.geometry),area:num(r.properties?.Surf_ha)||0,commune:restorationCommune(r.properties),technology:restorationTechnology(r.properties)}));
  const area=restorations.reduce((sum:number,r:any)=>sum+r.area,0),basinHa=Math.abs((num(feature.properties?.Shape_Area)||0)/10000);
  const techMap=new Map<string,{sites:number,area:number}>(),communeMap=new Map<string,{sites:number,area:number}>();
  for(const r of restorations){const t=techMap.get(r.technology)||{sites:0,area:0};t.sites++;t.area+=r.area;techMap.set(r.technology,t);const c=communeMap.get(r.commune)||{sites:0,area:0};c.sites++;c.area+=r.area;communeMap.set(r.commune,c)}
  const technologies=Array.from(techMap.entries()).map(([technology,v])=>({technology,...v})).sort((a,b)=>b.area-a.area);
  const communes=Array.from(communeMap.entries()).map(([commune,v])=>({commune,...v,part_pct:area?v.area/area*100:0})).sort((a,b)=>b.area-a.area);
  const modules:any={};for(const m of["pluviometrie","piezometrie","limnimetrie"]){const cfg=CFG[m];const loaded=await selectModuleRows(m,"","",cfg);modules[m]=loaded.rows.filter((r:any)=>validGps(r)&&inside([Number(r.longitude),Number(r.latitude)],feature.geometry))}
  return{id:sbId,feature,basinHa,restArea:area,density:basinHa?area/basinHa*100:0,restCount:restorations.length,restorations,technologies,communes,modules}
}
export async function GET(req:NextRequest){const sp=req.nextUrl.searchParams,publicMode=sp.get("public")==="1",module=sp.get("module")||"pluviometrie",format=(sp.get("format")||"pdf").toLowerCase(),periode=sp.get("periode")||"mensuel",start=sp.get("start")||periodStart(periode),end=sp.get("end")||"";if(!publicMode){const auth=await requireApiRole(req,[ROLE_DNH,ROLE_ADMIN,ROLE_SUPER_ADMIN]);if("response"in auth)return auth.response}else if(!["pluviometrie","piezometrie","limnimetrie"].includes(module)||!["pdf","csv"].includes(format)){return NextResponse.json({ok:false,error:"Rapport public non autorisé pour ce module/format."},{status:403})}
 if(module==="sous_bassin"){
  const sb=sp.get("sb")||"";if(!sb)return NextResponse.json({ok:false,error:"Identifiant de sous-bassin requis"},{status:400});
  try{
    const d=await subBasinData(sb);
    const rows=[{Sous_bassin:`SB-${d.id}`,Surface_ha:Math.abs(d.basinHa),Surface_restauree_ha:Math.abs(d.restArea),Densite_restauration_pct:d.density,Sites_restauration:d.restCount,Observations_pluvio:d.modules.pluviometrie.length,Mesures_piezo:d.modules.piezometrie.length,Lectures_limni:d.modules.limnimetrie.length}];
    const communeRows=d.communes.map((x:any)=>({Commune:x.commune,Nombre_sites:x.sites,Surface_restauree_ha:Math.abs(x.area),Part_pct:x.part_pct}));
    const techRows=d.technologies.map((x:any)=>({Technologie:x.technology,Nombre_sites:x.sites,Surface_restauree_ha:Math.abs(x.area)}));
    if(format==="csv")return new Response(csv(rows.concat(communeRows as any)),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="psore_SB-${sb}.csv"`}});
    if(format==="xlsx"){
      const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),"Synthèse sous-bassin");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(communeRows),"Répartition communale");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(techRows),"Technologies");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d.modules.pluviometrie),"Pluviométrie");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d.modules.piezometrie),"Piézométrie");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d.modules.limnimetrie),"Limnimétrie");return new Response(XLSX.write(wb,{type:"array",bookType:"xlsx"}),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="psore_SB-${sb}.xlsx"`}})
    }
    if(format==="docx"){
      const children:any[]=[new Paragraph({text:`PSORE — Rapport intégré du sous-bassin SB-${sb}`,heading:HeadingLevel.TITLE}),new Paragraph(`Surface absolue du sous-bassin : ${fr(Math.abs(d.basinHa))} ha ; surface restaurée : ${fr(Math.abs(d.restArea))} ha ; densité : ${fr(d.density)} %.`),new Paragraph(`Pluviométrie : ${d.modules.pluviometrie.length} observation(s). Piézométrie : ${d.modules.piezometrie.length} mesure(s). Limnimétrie : ${d.modules.limnimetrie.length} lecture(s).`),new Paragraph({text:"Répartition communale des restaurations",heading:HeadingLevel.HEADING_1})];
      for(const x of communeRows)children.push(new Paragraph(`• ${x.Commune} : ${x.Nombre_sites} site(s), ${fr(x.Surface_restauree_ha)} ha (${fr(x.Part_pct,1)} %).`));children.push(new Paragraph({text:"Technologies de restauration",heading:HeadingLevel.HEADING_1}));for(const x of techRows)children.push(new Paragraph(`• ${x.Technologie} : ${x.Nombre_sites} site(s), ${fr(x.Surface_restauree_ha)} ha.`));children.push(new Paragraph("Interprétation : les associations spatiales et temporelles constituent des éléments d'aide à la décision et ne prouvent pas à elles seules une causalité."));
      const doc=new Document({sections:[{children}]});const b=await Packer.toBuffer(doc);return new Response(new Uint8Array(b),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","Content-Disposition":`attachment; filename="psore_SB-${sb}.docx"`}})
    }
    const p=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});fill(p,C.navy);p.rect(0,0,297,28,"F");ink(p,"#FFFFFF");p.setFontSize(19);p.text(`PSORE — Rapport intégré du sous-bassin SB-${sb}`,14,13);brand(p);card(p,14,36,58,"Surface du sous-bassin",`${fr(Math.abs(d.basinHa))} ha`,C.blue);card(p,76,36,58,"Surface restaurée",`${fr(Math.abs(d.restArea))} ha`,C.green);card(p,138,36,58,"Densité restauration",`${fr(d.density)} %`,C.orange);card(p,200,36,58,"Sites restaurés",String(d.restCount),C.purple);drawSubBasinExcerpt(p,d,14,70,150,96);
    ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(10);p.text("Répartition communale",174,72);p.setFont("helvetica","normal");let yy=81;for(const x of communeRows.slice(0,8)){ink(p,C.navy);p.setFontSize(7);p.text(`${x.Commune} : ${x.Nombre_sites} site(s) · ${fr(x.Surface_restauree_ha)} ha · ${fr(x.Part_pct,1)} %`,174,yy);yy+=7}ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(10);p.text("Technologies de restauration",174,yy+3);p.setFont("helvetica","normal");yy+=12;for(const x of techRows.slice(0,8)){ink(p,C.gray);p.setFontSize(6.5);const z=p.splitTextToSize(`${x.Technologie} : ${x.Nombre_sites} site(s) · ${fr(x.Surface_restauree_ha)} ha`,105);p.text(z,174,yy);yy+=z.length*4+2;if(yy>186)break}addFooter(p,"PSORE/PTCS ; couches SIG et restaurations fournies au projet");return new Response(p.output("arraybuffer"),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="psore_SB-${sb}.pdf"`}})
  }catch(e:any){return NextResponse.json({ok:false,error:e.message||"Rapport sous-bassin impossible"},{status:500})}
 }
 const cfg=CFG[module];if(!cfg)return NextResponse.json({ok:false,error:"Module non supporté"},{status:400});if(start&&end&&start>end)return NextResponse.json({ok:false,error:"Période invalide : la date de début est postérieure à la date de fin."},{status:400});try{const loaded=await selectModuleRows(module,start,end,cfg),raw=loaded.rows,q=quality(raw,module,cfg),s=stats(q,module,cfg),a=analysis(q,module,cfg,s,start,end),rows=reportRows(q,module,cfg),mapRows=await networkMapRows(module,q),periodLabel=`du ${start||"début disponible"} au ${end||s.last}`,source="données PSORE/PTCS ; fond cartographique © contributeurs OpenStreetMap ; limites administratives : Communes_Projet_enabel et couches SIG fournies au projet";if(loaded.rejected>0)a.lines.push(`${loaded.rejected} enregistrement(s) n’ont pas pu être rapprochés d’une station du référentiel canonique.`);if(hydro(module)&&loaded.historicalCount>=0)a.lines.push(`Historique synchronisé : ${loaded.historicalCount} mesure(s) parent/enfant rapprochée(s). Seuil opérationnel : ${loaded.cutoff||"non défini"}.`);if(hydro(module)&&loaded.futureCount>0)a.lines.push(`${loaded.futureCount} donnée(s) à date future ont été classées « À vérifier » et exclues provisoirement des calculs.`);if(publicMode){for(let i=0;i<rows.length;i++){delete rows[i]["Observateur"];delete rows[i]["Commentaire"];}}
 if(format==="csv")return new Response(csv(rows),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="psore_${module}_${periode}.csv"`}});
 if(format==="xlsx"){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Indicateur:"Enregistrements",Valeur:s.n},{Indicateur:"Stations du réseau",Valeur:s.total},{Indicateur:"Stations avec données",Valeur:s.stations},{Indicateur:"Taux de couverture (%)",Valeur:s.cov},{Indicateur:"Moyenne",Valeur:s.avg??"Non renseigné"},{Indicateur:"Minimum",Valeur:s.min??"Non renseigné"},{Indicateur:"Maximum",Valeur:s.max??"Non renseigné"},{Indicateur:"Dernière observation",Valeur:s.last}]),"Synthèse");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(a.lines.map((x,i)=>({N:i+1,Observation:x}))),"Analyse");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),"Détail des données");return new Response(XLSX.write(wb,{type:"array",bookType:"xlsx"}),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="psore_${module}_${periode}.xlsx"`}})}
 if(format==="docx"){const hs=rows.length?Object.keys(rows[0]):cfg.cols.map((x:any)=>x[1]);const header=new TableRow({children:hs.map((h:string)=>new TableCell({shading:{fill:"0877B9"} as any,children:[new Paragraph({children:[new TextRun({text:h,bold:true,color:"FFFFFF"})]})]}))}),trs=[header].concat(rows.slice(0,1500).map(r=>new TableRow({children:hs.map(h=>new TableCell({children:[new Paragraph(text(r[h]))]}))})));const docChildren:any[]=[new Paragraph({text:cfg.title,heading:HeadingLevel.TITLE}),new Paragraph(`Rapport technique — Période ${periodLabel}`),new Paragraph({text:"Indicateurs de synthèse",heading:HeadingLevel.HEADING_1}),new Paragraph(`Enregistrements : ${s.n} ; réseau : ${s.total} ; stations avec données : ${s.stations} ; couverture : ${fr(s.cov,1)} % ; moyenne : ${fr(s.avg)} ${cfg.unit}.`),new Paragraph({text:"Analyse automatique",heading:HeadingLevel.HEADING_1}),...a.lines.map(x=>new Paragraph(`• ${x}`)),new Paragraph({text:"Tableau détaillé",heading:HeadingLevel.HEADING_1}),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:trs})];const doc=new Document({sections:[{children:docChildren}]});const b=await Packer.toBuffer(doc);return new Response(new Uint8Array(b),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","Content-Disposition":`attachment; filename="psore_${module}_${periode}.docx"`}})}
 if(format==="pdf"){const p=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});fill(p,C.navy);p.rect(0,0,297,28,"F");ink(p,"#FFFFFF");p.setFont("helvetica","bold");p.setFontSize(18);p.text(cfg.title,14,11);p.setFont("helvetica","normal");p.setFontSize(8);p.text(`Rapport technique — Période ${periodLabel}`,14,19);brand(p);card(p,12,34,42,"Enregistrements",String(s.n),C.blue);card(p,57,34,42,"Réseau",String(s.total),C.purple);card(p,102,34,42,"Avec données",String(s.stations),C.green);card(p,147,34,42,"Couverture",`${fr(s.cov,1)} %`,C.cyan);card(p,192,34,43,"Moyenne",s.avg===null?"Non renseigné":`${fr(s.avg)} ${cfg.unit}`,C.orange);card(p,238,34,47,"Dernière obs.",s.last,C.blue);drawChart(p,q,module,cfg,12,67,132,48);await osmMap(p,mapRows,module,154,67,131,67);ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(10);p.text("Analyse automatique",12,128);p.setFont("helvetica","normal");ink(p,C.gray);p.setFontSize(7);let yy=135;for(let i=0;i<a.lines.length;i++){const z=p.splitTextToSize(`• ${a.lines[i]}`,128);p.text(z,12,yy);yy+=z.length*3.6+1;if(yy>192)break}ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(9);p.text("Contrôles",154,143);p.setFont("helvetica","normal");ink(p,C.gray);p.setFontSize(7);p.text(`À vérifier : ${a.qa.verifier}  •  Incomplètes : ${a.qa.incomplets}  •  Doublons potentiels : ${a.qa.doublons}  •  Valeurs atypiques : ${a.qa.atypiques}`,154,151);p.text("Valeur atypique = valeur nécessitant une vérification ; aucune observation n'est supprimée automatiquement.",154,158);p.text("Formules : couverture = stations avec données ÷ stations du réseau × 100 ; moyenne = somme des valeurs valides ÷ nombre de valeurs valides.",154,165);p.text("Une valeur 0 est conservée comme mesure ; une cellule vide est exclue des calculs.",154,172);if(module==="pluviometrie"){const codes=distinctOfficialSites("pluviometrie",q);const cum=q.map(r=>num(r.pluie_24h_mm)).filter((x):x is number=>x!==null).reduce((aa,bb)=>aa+bb,0);p.text(codes.size===1?`Cumul pluviométrique de la période : ${fr(cum)} mm.`:"Cumul global de période : Non applicable à plusieurs stations ; les cumuls sont présentés station par station.",154,179);}
 const hs=rows.length?Object.keys(rows[0]):[];p.addPage("a4","landscape");let y=18;const widths=hs.map(()=>272/Math.max(1,hs.length));const head=()=>{fill(p,C.blue);p.rect(12,y-4,273,8,"F");ink(p,"#FFFFFF");p.setFont("helvetica","bold");p.setFontSize(5.2);hs.forEach((h,i)=>p.text(h.slice(0,23),13+widths.slice(0,i).reduce((a,b)=>a+b,0),y));p.setFont("helvetica","normal");y+=8};head();for(let i=0;i<rows.length;i++){if(y>196){p.addPage("a4","landscape");y=14;head()}if(i%2===0){fill(p,"#F7FAFC");p.rect(12,y-3,273,4.2,"F")}ink(p,C.navy);p.setFontSize(4.9);hs.forEach((h,j)=>p.text(text(rows[i][h]).replace(/\s+/g," ").slice(0,29),13+widths.slice(0,j).reduce((a,b)=>a+b,0),y));y+=4.2}addFooter(p,source);return new Response(p.output("arraybuffer"),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="psore_${module}_${periode}.pdf"`}})}return NextResponse.json({ok:false,error:"Format non supporté"},{status:400})}catch(e:any){return NextResponse.json({ok:false,error:e.message||"Génération impossible"},{status:500})}}
