"use client";

import { useEffect, useMemo, useState } from "react";
import Kpi from "@/components/Kpi";
import LeafletMap from "@/components/map/LeafletMap";
import MiniBarChart from "@/components/dashboard/MiniBarChart";
import { downloadAuthenticated } from "@/lib/download-client";
import { useRole } from "@/components/auth/useRole";

type ModuleName = "pluviometrie" | "piezometrie" | "limnimetrie";
const moduleLabels: Record<ModuleName, string> = { pluviometrie: "Pluviométrie", piezometrie: "Piézométrie", limnimetrie: "Limnimétrie" };
const valueLabels: Record<ModuleName, string> = { pluviometrie: "Pluie 24h", piezometrie: "Niveau statique", limnimetrie: "Hauteur d’eau" };
const unitLabels: Record<ModuleName, string> = { pluviometrie: "mm", piezometrie: "m", limnimetrie: "m / cm" };
function v(x: any) { return x === null || x === undefined || x === "" ? "--" : String(x); }
function fmtNumber(x: any, unit = "") { if (x === null || x === undefined || x === "") return "--"; const n = Number(x); if (!Number.isFinite(n)) return String(x); return `${Math.round(n * 100) / 100}${unit ? ` ${unit}` : ""}`; }
function buildParams(filters: Record<string, string>) { const params = new URLSearchParams(); for (const [k,val] of Object.entries(filters)) if (val && val !== "all") params.set(k,val); return params; }
function interpretation(module: ModuleName, stats: any) { const alerts=Number(stats.alertes||0),obs=Number(stats.observations||0),future=Number(stats.donnees_futures_a_verifier||0); if(future>0)return `${future} donnée(s) portent une date future et sont exclues provisoirement des calculs.`;if(!obs)return "Aucune observation validée pour ce filtre.";if(alerts>0)return `${alerts} donnée(s) nécessitent une vérification. Elles restent conservées dans la source mais sont exclues des indicateurs validés.`;if(module==="piezometrie"&&stats.remontee_moyenne_m!==null)return `Sur la période sélectionnée, la remontée moyenne pondérée est de ${fmtNumber(stats.remontee_moyenne_m,"m")} (${fmtNumber(stats.taux_moyen_communes_pct,"%")}). Un taux global station de ${fmtNumber(stats.taux_global_stations_pct,"%")} est également calculé.`;if(module==="limnimetrie")return "Les mesures limnimétriques représentent le niveau des cours d’eau au droit des stations où elles sont implantées.";if(module==="pluviometrie")return "Les relevés pluviométriques filtrés permettent de suivre les précipitations et leurs cumuls sur les stations du réseau.";return "Les mesures validées sont affichées selon les filtres sélectionnés."; }

export default function ThematicModuleDashboard({ module }: { module: ModuleName }) {
  const { canExportCsvXlsx } = useRole(); const [json,setJson]=useState<any>(null);const [loading,setLoading]=useState(false);const [commune,setCommune]=useState("all");const [site,setSite]=useState("all");const [alerte,setAlerte]=useState("all");const [start,setStart]=useState("");const [end,setEnd]=useState("");const [refreshToken,setRefreshToken]=useState(0);const [exporting,setExporting]=useState("");const [exportError,setExportError]=useState("");
  const params=useMemo(()=>buildParams({module,commune,site,alerte,start,end}),[module,commune,site,alerte,start,end]);
  useEffect(()=>{setLoading(true);fetch(`/api/dashboard/module?${params.toString()}`,{cache:"no-store"}).then(r=>r.json()).then(setJson).finally(()=>setLoading(false));},[params,refreshToken]);
  useEffect(()=>{const onSync=(event:Event)=>{const detail=(event as CustomEvent).detail;if(!detail?.module||detail.module===module)setRefreshToken(x=>x+1)};window.addEventListener("psore-sync-complete",onSync);return()=>window.removeEventListener("psore-sync-complete",onSync)},[module]);
  const stats=json?.stats||{},rows=json?.data||[],filters=json?.filters||{};
  async function exportData(format:"csv"|"xlsx"){setExporting(format);setExportError("");try{await downloadAuthenticated(`/api/reports/export-v3?module=${module}&format=${format}${start?`&start=${start}`:""}${end?`&end=${end}`:""}`,`PSORE_${module}.${format}`)}catch(e:any){setExportError(e?.message||"Export impossible")}finally{setExporting("")}}
  return <>
    <div className="panel filters-panel"><div><h2>Analyse dynamique — {moduleLabels[module]}</h2><p className="muted">KPI, filtres, carte, évolution, qualité des données et exports. Source : {json?.source||"chargement"}</p></div>
      <div className="filters-grid compact filters-grid-wide"><label><span>Commune</span><select className="input" value={commune} onChange={e=>{setCommune(e.target.value);setSite("all")}}><option value="all">Toutes</option>{(filters.communes||[]).map((c:string)=><option key={c} value={c}>{c}</option>)}</select></label><label><span>Site / station</span><select className="input" value={site} onChange={e=>setSite(e.target.value)}><option value="all">Tous</option>{(filters.sites||[]).map((s:string)=><option key={s} value={s}>{s}</option>)}</select></label><label><span>Alerte</span><select className="input" value={alerte} onChange={e=>setAlerte(e.target.value)}><option value="all">Toutes</option><option value="yes">À vérifier</option><option value="no">Validées</option></select></label><label><span>Début</span><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label><span>Fin</span><input className="input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>
      <div className="quick-actions">{canExportCsvXlsx&&<button className="btn btn-primary" disabled={!!exporting} onClick={()=>exportData("csv")}>{exporting==="csv"?"Téléchargement…":"Exporter CSV validé"}</button>}{canExportCsvXlsx&&<button className="btn btn-soft" disabled={!!exporting} onClick={()=>exportData("xlsx")}>{exporting==="xlsx"?"Téléchargement…":"Exporter Excel"}</button>}<button className="btn btn-soft" onClick={()=>{setCommune("all");setSite("all");setAlerte("all");setStart("");setEnd("")}}>Réinitialiser</button></div>{exportError&&<div className="alert warn" style={{marginTop:10}}>{exportError}</div>}
    </div>
    <div className="grid-4" style={{marginTop:18}}><Kpi label="Observations validées" value={v(stats.observations)} hint="Après contrôle qualité"/><Kpi label="Sites du réseau" value={v(stats.sites)} hint={`${v(stats.sites_avec_donnees)} avec données · couverture ${v(stats.couverture_pct)}%`}/><Kpi label={`Moyenne ${unitLabels[module]}`} value={fmtNumber(stats.moyenne)} hint={valueLabels[module]}/><Kpi label="À vérifier" value={v(stats.alertes)} hint="Exclues des indicateurs"/></div>
    {module==="piezometrie"&&<div className="grid-4" style={{marginTop:18}}><Kpi label="Remontée moyenne" value={fmtNumber(stats.remontee_moyenne_m,"m")} hint="Moyenne des communes, pondérée par mesures"/><Kpi label="Taux moyen des communes" value={fmtNumber(stats.taux_moyen_communes_pct,"%")} hint="Moyenne des taux communaux"/><Kpi label="Remontée globale stations" value={fmtNumber(stats.remontee_global_stations_m,"m")} hint="Calcul pondéré par mesures"/><Kpi label="Taux global stations" value={fmtNumber(stats.taux_global_stations_pct,"%")} hint="Calcul pondéré par mesures"/></div>}
    <div className="grid-4" style={{marginTop:18}}><Kpi label="Minimum" value={fmtNumber(stats.minimum)} hint={valueLabels[module]}/><Kpi label="Maximum" value={fmtNumber(stats.maximum)} hint={valueLabels[module]}/><Kpi label="Sans GPS" value={v(stats.sans_gps)} hint="Sites non cartographiables"/><Kpi label="Dernière donnée" value={v(stats.derniere_observation)} hint="Date observation"/></div>
    <div className="panel" style={{marginTop:18}}><h2>Interprétation automatique</h2><p className="muted">{loading?"Analyse en cours...":interpretation(module,stats)}</p></div>
    <div className="grid-2" style={{marginTop:18}}><MiniBarChart title="Répartition par commune" data={(json?.charts?.communes||[]).slice(0,10)}/><MiniBarChart title="Évolution récente" data={(json?.charts?.evolution||[]).slice(-12)}/></div>
    <div className="grid-2" style={{marginTop:18}}><MiniBarChart title="Top sites / stations" data={(json?.charts?.sites||[]).slice(0,10)}/><MiniBarChart title="Alertes par type" data={(json?.charts?.alertes||[]).slice(0,10)}/></div>
    <div className="panel" style={{marginTop:18}}><h2>Carte du module</h2><LeafletMap module={module}/></div>
    <div className="panel" style={{marginTop:18}}><h2>Données récentes</h2><div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Site</th><th>Commune</th><th>{valueLabels[module]}</th><th>Statut</th><th>Observateur</th><th>Commentaire</th></tr></thead><tbody>{rows.slice(0,150).map((r:any,i:number)=>{const alert=Boolean(r.alerte_valeur||r.alerte_gps||r.alerte_donnee);return <tr key={r.id||i}><td>{v(r.date_observation)}</td><td>{v(r.code_site||r.code_station||r.code_piezo)}</td><td>{v(r.commune)}</td><td>{fmtNumber(r.valeur_observee||r.pluie_24h_mm||r.niveau_statique||r.hauteur_eau)}</td><td><span className={alert?"badge danger":"badge ok"}>{alert?"À vérifier":"Validée"}</span></td><td>{v(r.observateur)}</td><td>{v(r.commentaire)}</td></tr>})}{!rows.length&&<tr><td colSpan={7}>Aucune donnée pour les filtres sélectionnés.</td></tr>}</tbody></table></div></div>
  </>;
}
