export const dynamic = "force-dynamic";
export const revalidate = 0;
export const fetchCache = "force-no-store";
export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { requireApiRole } from "@/lib/auth-server";
import { ROLE_ADMIN, ROLE_DNH, ROLE_SUPER_ADMIN } from "@/lib/permissions";
import { loadHydroRows, type HydroRow } from "@/lib/hydro-data";
import { stationMetaByCode, displayStationCode, type HydroModule } from "@/lib/network-registry";

type Hydro = "pluviometrie" | "piezometrie" | "limnimetrie";
const HYDRO: Hydro[] = ["pluviometrie", "piezometrie", "limnimetrie"];
const CFG: Record<Hydro,{value:string;unit:string;title:string}> = {
  pluviometrie:{value:"pluie_24h_mm",unit:"mm",title:"Rapport de suivi pluviométrique"},
  piezometrie:{value:"niveau_statique",unit:"m",title:"Rapport de suivi piézométrique"},
  limnimetrie:{value:"hauteur_eau",unit:"cm",title:"Rapport de suivi limnimétrique"},
};
const C={navy:"#0B2545",blue:"#0877B9",cyan:"#37B6D4",purple:"#58369A",green:"#1F9D63",orange:"#D97706",red:"#C2413A",gray:"#5F6F82",line:"#D9E5EF",light:"#F7FAFC"};
const TREND={strongRise:10,rise:5,stableLow:-5,decline:-10};
const t=(v:any)=>String(v??"").trim();
const n=(v:any):number|null=>{if(v===null||v===undefined||v==="")return null;const x=Number(String(v).replace(",","."));return Number.isFinite(x)?x:null};
const dt=(v:any)=>t(v).slice(0,10);
const norm=(v:any)=>t(v).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const fmt=(v:any,d=2)=>{const x=n(v);return x===null?"—":x.toLocaleString("fr-FR",{minimumFractionDigits:d,maximumFractionDigits:d})};
const signed=(v:any,d=2)=>{const x=n(v);return x===null?"—":`${x>0?"+":""}${x.toLocaleString("fr-FR",{minimumFractionDigits:d,maximumFractionDigits:d})}`};
const finite=(v:any,f=0)=>{const x=Number(v);return Number.isFinite(x)?x:f};
const rgb=(h:string):[number,number,number]=>{const x=h.replace("#","");return[parseInt(x.slice(0,2),16),parseInt(x.slice(2,4),16),parseInt(x.slice(4,6),16)]};
const fill=(p:jsPDF,c:string)=>p.setFillColor(...rgb(c));
const ink=(p:jsPDF,c:string)=>p.setTextColor(...rgb(c));
const stroke=(p:jsPDF,c:string)=>p.setDrawColor(...rgb(c));
const gps=(r:any)=>{const la=n(r.latitude),lo=n(r.longitude);return la!==null&&lo!==null&&la>=-90&&la<=90&&lo>=-180&&lo<=180};
const code=(m:Hydro,r:any)=>{const raw=t(r.code_site||r.code_station||r.code_piezo);const meta=stationMetaByCode(m as HydroModule,raw);return meta?displayStationCode(m as HydroModule,meta.code):raw};
const hour=(r:any)=>{const raw=t(r.heure_observation||r.heure||r.time||r.timestamp);const m=raw.match(/(?:T|\s)(\d{1,2}:\d{2})/);return m?m[1].padStart(5,"0"):raw.slice(0,5)};
const split=(v:string)=>v.split(",").map(x=>norm(x)).filter(Boolean);
function applyFilters(rows:any[],sp:URLSearchParams){const cs=split(sp.get("communes")||sp.get("commune")||""),ls=split(sp.get("localites")||sp.get("localite")||""),ss=split(sp.get("stations")||sp.get("station")||"");return rows.filter(r=>(!cs.length||cs.includes(norm(r.commune)))&&(!ls.length||ls.includes(norm(r.nom_site||r.localite||r.village)))&&(!ss.length||ss.includes(norm(r.code_site||r.code_station||r.code_piezo))))}
function territory(rows:any[],sp:URLSearchParams){const raw=sp.get("communes")||sp.get("commune")||"";if(raw.trim())return raw.split(",").map(x=>x.trim()).filter(Boolean).join(" + ");const cs=[...new Set(rows.map(r=>t(r.commune)).filter(Boolean))];return cs.length?cs.join(" + "):"Territoire PTCS"}
function usable(rows:HydroRow[],m:Hydro){const seen=new Set<string>();return rows.map((r:any)=>{const station=t(r.code_site||r.code_station||r.code_piezo),date=dt(r.date_observation),h=hour(r),value=n(r[CFG[m].value]),key=`${station}|${date}|${h}|${value??""}`,incomplete=!station||!/^\d{4}-\d{2}-\d{2}$/.test(date)||value===null,future=/^\d{4}-\d{2}-\d{2}$/.test(date)&&date>new Date().toISOString().slice(0,10),duplicate=seen.has(key);seen.add(key);return{...r,__usable:!incomplete&&!future&&!duplicate,__duplicate:duplicate}})}
function weighted(xs:{value:number;weight:number}[]){const c=xs.filter(x=>Number.isFinite(x.value)&&Number.isFinite(x.weight)&&x.weight>0),w=c.reduce((a,x)=>a+x.weight,0);return w?c.reduce((a,x)=>a+x.value*x.weight,0)/w:null}
function trend(rate:number|null){if(rate===null)return"Tendance non calculable";if(rate>TREND.strongRise)return"Remontée marquée";if(rate>TREND.rise)return"Remontée";if(rate>=TREND.stableLow)return"Relativement stable";if(rate>=TREND.decline)return"Baisse";return"Baisse marquée"}
function piezo(rows:any[]){const u=rows.filter(r=>r.__usable),by=new Map<string,any[]>();for(const r of u){const k=code("piezometrie",r),a=by.get(k)||[];a.push(r);by.set(k,a)}const stations:any[]=[];for(const[k,a]of by){a.sort((x,y)=>dt(x.date_observation).localeCompare(dt(y.date_observation))||hour(x).localeCompare(hour(y)));const first=n(a[0]?.niveau_statique),last=n(a[a.length-1]?.niveau_statique),eligible=a.length>=2&&first!==null&&last!==null&&first!==0,delta=first!==null&&last!==null?first-last:null,rate=eligible&&delta!==null?delta/first!*100:null;stations.push({code:k,localite:t(a[0]?.nom_site||a[0]?.localite||a[0]?.village),commune:t(a[0]?.commune),initial:first,final:last,evolution:delta,taux:rate,tendance:trend(rate),mesures:a.length,eligible})}const el=stations.filter(s=>s.eligible),evolution=weighted(el.map(s=>({value:s.evolution,weight:s.mesures}))),taux=weighted(el.map(s=>({value:s.taux,weight:s.mesures}))),levels=u.map(r=>n(r.niveau_statique)).filter((x):x is number=>x!==null),cm=new Map<string,any[]>();for(const s of el){const a=cm.get(s.commune)||[];a.push(s);cm.set(s.commune,a)}const communes=[...cm].map(([commune,a])=>({commune,evolution:weighted(a.map(s=>({value:s.evolution,weight:s.mesures}))),taux:weighted(a.map(s=>({value:s.taux,weight:s.mesures})))}));const avgComm=communes.length?communes.reduce((s,c)=>s+finite(c.taux),0)/communes.length:null;return{stations,communes,evolution,taux,avgComm,niveauMoyen:levels.length?levels.reduce((a,b)=>a+b,0)/levels.length:null,tendance:trend(taux),down:stations.filter(s=>s.taux!==null&&s.taux<TREND.stableLow).length,stable:stations.filter(s=>s.taux!==null&&s.taux>=TREND.stableLow&&s.taux<=TREND.rise).length,up:stations.filter(s=>s.taux!==null&&s.taux>TREND.rise).length}}
function rain(rows:any[]){const u=rows.filter(r=>r.__usable),xs=u.map(r=>n(r.pluie_24h_mm)).filter((x):x is number=>x!==null),by=new Map<string,any>();for(const r of u){const k=code("pluviometrie",r),x=n(r.pluie_24h_mm);if(x===null)continue;const z=by.get(k)||{code:k,localite:t(r.nom_site||r.localite||r.village),commune:t(r.commune),values:[] as number[]};z.values.push(x);by.set(k,z)}return{average:xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null,total:xs.reduce((a,b)=>a+b,0),min:xs.length?Math.min(...xs):null,max:xs.length?Math.max(...xs):null,rainyDays:new Set(u.filter(r=>(n(r.pluie_24h_mm)||0)>=.1).map(r=>dt(r.date_observation))).size,stations:[...by.values()].map(z=>({...z,cumul:z.values.reduce((a:number,b:number)=>a+b,0),moyenne:z.values.reduce((a:number,b:number)=>a+b,0)/z.values.length,max:Math.max(...z.values),jours_pluvieux:z.values.filter((x:number)=>x>=.1).length}))}}
function limni(rows:any[]){const u=rows.filter(r=>r.__usable),by=new Map<string,any>();for(const r of u){const k=code("limnimetrie",r),x=n(r.hauteur_eau);if(x===null)continue;const z=by.get(k)||{code:k,localite:t(r.nom_site||r.localite||r.village),commune:t(r.commune),cours_eau:t(r.cours_eau||r.nom_cours_eau||r.nom_site||r.localite),values:[] as number[]};z.values.push(x);by.set(k,z)}const stations=[...by.values()].map(z=>({...z,moyenne:z.values.reduce((a:number,b:number)=>a+b,0)/z.values.length,minimum:Math.min(...z.values),maximum:Math.max(...z.values),mesures:z.values.length})),all=stations.flatMap(s=>s.values);return{stations,moyenne:all.length?all.reduce((a:number,b:number)=>a+b,0)/all.length:null,minimum:all.length?Math.min(...all):null,maximum:all.length?Math.max(...all):null}}
function card(p:jsPDF,x:number,y:number,w:number,label:string,value:string,color:string){if(![x,y,w].every(Number.isFinite))return;fill(p,"#FFFFFF");stroke(p,C.line);p.roundedRect(x,y,w,21,3,3,"FD");fill(p,color);p.roundedRect(x,y,3,21,2,2,"F");ink(p,C.gray);p.setFont("helvetica","normal");p.setFontSize(5.5);p.text(t(label),x+6,y+6);ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(9);p.text(t(value).slice(0,34),x+6,y+16)}
function communeFeatures(rows:any[],sp:URLSearchParams){try{const gj:any=JSON.parse(readFileSync(join(process.cwd(),"public/data/decisionnel/communes_projet_enabel.geojson"),"utf8"));const wanted=split(sp.get("communes")||sp.get("commune")||"");const rowNames=[...new Set(rows.map(r=>norm(r.commune)).filter(Boolean))];return(gj.features||[]).filter((f:any)=>{const name=norm(f?.properties?.laa||f?.properties?.commune||f?.properties?.name);return wanted.length?wanted.includes(name):rowNames.includes(name)})}catch{return[]}}
function coordsOf(g:any){const out:number[][]=[];const walk=(x:any)=>{if(Array.isArray(x)&&x.length>=2&&typeof x[0]==="number"&&typeof x[1]==="number"&&Number.isFinite(x[0])&&Number.isFinite(x[1]))out.push([x[0],x[1]]);else if(Array.isArray(x))x.forEach(walk)};walk(g?.coordinates);return out}
async function map(p:jsPDF,rows:any[],m:Hydro,sp:URLSearchParams,x:number,y:number,w:number,h:number){const pts=new Map<string,{lat:number;lon:number;label:string}>();for(const r of rows){if(!gps(r))continue;const k=code(m,r);if(k&&!pts.has(k))pts.set(k,{lat:finite(r.latitude),lon:finite(r.longitude),label:k})}const pp=[...pts.values()],features=communeFeatures(rows,sp),poly=features.flatMap((f:any)=>coordsOf(f.geometry));const lons=[...pp.map(a=>a.lon),...poly.map(a=>a[0])],lats=[...pp.map(a=>a.lat),...poly.map(a=>a[1])];fill(p,C.light);stroke(p,C.line);p.roundedRect(x,y,w,h,2,2,"FD");ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(7);p.text("Carte du territoire filtré",x+2,y-3);if(!lons.length||!lats.length){ink(p,C.gray);p.setFontSize(5);p.text("Aucune géométrie disponible",x+4,y+10);return}let minLon=Math.min(...lons),maxLon=Math.max(...lons),minLat=Math.min(...lats),maxLat=Math.max(...lats);const dx=Math.max(maxLon-minLon,.01),dy=Math.max(maxLat-minLat,.01);minLon-=dx*.08;maxLon+=dx*.08;minLat-=dy*.08;maxLat+=dy*.08;const DX=Math.max(maxLon-minLon,.01),DY=Math.max(maxLat-minLat,.01);const px=(lon:number)=>x+4+(lon-minLon)/DX*(w-8),py=(lat:number)=>y+h-5-(lat-minLat)/DY*(h-10);let bg=false;try{const z=8,N=2**z,cLon=(minLon+maxLon)/2,cLat=(minLat+maxLat)/2,tx=Math.floor((cLon+180)/360*N),rad=cLat*Math.PI/180,ty=Math.floor((1-Math.log(Math.tan(rad)+1/Math.cos(rad))/Math.PI)/2*N),sat=(sp.get("basemap")||"").toLowerCase()==="satellite",url=sat?`https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${z}/${ty}/${tx}`:`https://tile.openstreetmap.org/${z}/${tx}/${ty}.png`,rr=await fetch(url,{headers:{"User-Agent":"PSORE-PTCS/5"}});if(rr.ok){const ab=await rr.arrayBuffer();p.addImage(new Uint8Array(ab),sat?"JPEG":"PNG",x+1,y+1,w-2,h-2);bg=true}}catch{}
  stroke(p,"#155E75");p.setLineWidth(.5);for(const f of features){const rings=f.geometry?.type==="Polygon"?[f.geometry.coordinates?.[0]||[]]:(f.geometry?.type==="MultiPolygon"?(f.geometry.coordinates||[]).map((a:any)=>a?.[0]||[]):[]);for(const ring of rings){for(let i=1;i<ring.length;i++){const a=ring[i-1],b=ring[i];if(!a||!b)continue;const x1=px(a[0]),y1=py(a[1]),x2=px(b[0]),y2=py(b[1]);if([x1,y1,x2,y2].every(Number.isFinite))p.line(x1,y1,x2,y2)}}}
  for(const pt of pp){const xx=px(pt.lon),yy=py(pt.lat);if(!Number.isFinite(xx)||!Number.isFinite(yy))continue;fill(p,C.purple);stroke(p,"#FFFFFF");p.circle(xx,yy,1.3,"FD")}
  ink(p,C.gray);p.setFontSize(4);p.text(bg?((sp.get("basemap")||"").toLowerCase()==="satellite"?"Fond satellite Esri":"Fond © OpenStreetMap"):"Fond cartographique indisponible lors de la génération",x+2,y+h-1.5);p.text(`${pp.length} station(s) géolocalisée(s)`,x+w-34,y+h-1.5)
}
function header(p:jsPDF,title:string,territory:string,period:string){fill(p,C.navy);p.rect(0,0,297,27,"F");ink(p,"#FFFFFF");p.setFont("helvetica","bold");p.setFontSize(14);p.text(`PSORE — ${title}`,12,11);p.setFont("helvetica","normal");p.setFontSize(6.5);p.text(`Territoire : ${territory} • Période : ${period}`,12,19)}
function footer(p:jsPDF){const pages=p.getNumberOfPages();for(let i=1;i<=pages;i++){p.setPage(i);ink(p,C.gray);p.setFontSize(4.5);p.text(`PSORE • PTCS – Enabel – DNH/DRHK • Production : ${new Date().toISOString().slice(0,10)}`,12,204);p.text(`Page ${i}/${pages}`,270,204)}}
function table(p:jsPDF,headers:string[],rows:string[][],y=134){ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(6.5);p.text("Détail par station",12,y);let yy=y+7;p.setFontSize(4.5);p.text(headers.join("   |   "),12,yy);p.setFont("helvetica","normal");for(const row of rows.slice(0,12)){yy+=5;if(yy>195)break;ink(p,C.gray);p.text(row.join("   |   ").slice(0,165),12,yy)}}
export async function GET(req:NextRequest){const auth=await requireApiRole(req,[ROLE_DNH,ROLE_ADMIN,ROLE_SUPER_ADMIN]);if("response" in auth)return auth.response;const sp=req.nextUrl.searchParams,m=(sp.get("module")||"pluviometrie") as Hydro;if(!HYDRO.includes(m))return NextResponse.json({ok:false,error:"Module invalide"},{status:400});try{const loaded=await loadHydroRows(m);let rows=applyFilters(loaded.rows,sp);const start=sp.get("start")||"",end=sp.get("end")||"";if(start)rows=rows.filter(r=>dt(r.date_observation)>=start);if(end)rows=rows.filter(r=>dt(r.date_observation)<=end);const checked=usable(rows,m),period=`${start||checked.map(r=>dt(r.date_observation)).filter(Boolean).sort()[0]||"début disponible"} → ${end||checked.map(r=>dt(r.date_observation)).filter(Boolean).sort().at(-1)||"fin disponible"}`,terr=territory(checked,sp),p=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});header(p,CFG[m].title,terr,period);
  if(m==="piezometrie"){const s=piezo(checked);card(p,12,33,50,"Niveau moyen",`${fmt(s.niveauMoyen)} m`,C.blue);card(p,66,33,58,"Évolution moyenne",`${signed(s.evolution)} m (${signed(s.taux,1)} %)`,C.cyan);card(p,128,33,48,"Moyenne communes",`${signed(s.avgComm,1)} %`,C.green);card(p,180,33,52,"Taux global pondéré",`${signed(s.taux,1)} %`,C.purple);card(p,236,33,49,"Tendance",s.tendance,s.tendance.includes("Baisse")?C.red:C.green);await map(p,checked,m,sp,151,68,134,58);ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(8);p.text("À retenir pour la décision",12,70);ink(p,C.gray);p.setFont("helvetica","normal");p.setFontSize(6);const decision=`Sur ${terr}, l’évolution moyenne du niveau statique est de ${signed(s.evolution)} m (${signed(s.taux,1)} %). La tendance observée est ${s.tendance.toLowerCase()}. ${s.down} station(s) présentent une baisse, ${s.stable} une situation relativement stable et ${s.up} une remontée.`;p.text(p.splitTextToSize(decision,132),12,79);let y=101;ink(p,C.navy);p.setFont("helvetica","bold");p.text("Analyse par commune",12,y);p.setFont("helvetica","normal");ink(p,C.gray);for(const c of s.communes.slice(0,6)){y+=7;p.text(`• ${c.commune} : évolution ${signed(c.evolution)} m · ${signed(c.taux,1)} %.`,12,y)}table(p,["Station","Localité","Commune","Initial","Final","Évolution","Tendance"],s.stations.map(x=>[x.code,x.localite,x.commune,fmt(x.initial),fmt(x.final),`${signed(x.evolution)} m`,x.tendance]),134)}
  if(m==="pluviometrie"){const s=rain(checked);card(p,12,33,50,"Pluie moyenne",`${fmt(s.average)} mm`,C.blue);card(p,66,33,50,"Cumul",`${fmt(s.total)} mm`,C.green);card(p,120,33,50,"Jours pluvieux",String(s.rainyDays),C.purple);card(p,174,33,50,"Maximum journalier",`${fmt(s.max)} mm`,C.orange);card(p,228,33,57,"Minimum journalier",`${fmt(s.min)} mm`,C.cyan);await map(p,checked,m,sp,151,68,134,58);ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(8);p.text("À retenir pour la décision",12,70);ink(p,C.gray);p.setFont("helvetica","normal");p.setFontSize(6);p.text(p.splitTextToSize(`Sur ${terr}, la pluie moyenne observée est de ${fmt(s.average)} mm, pour un cumul de ${fmt(s.total)} mm et ${s.rainyDays} jour(s) pluvieux. Le maximum journalier atteint ${fmt(s.max)} mm.`,132),12,79);table(p,["Station","Localité","Commune","Cumul","Moyenne","Max","Jours pluvieux"],s.stations.map(x=>[x.code,x.localite,x.commune,`${fmt(x.cumul)} mm`,`${fmt(x.moyenne)} mm`,`${fmt(x.max)} mm`,String(x.jours_pluvieux)]),115)}
  if(m==="limnimetrie"){const s=limni(checked);card(p,12,33,50,"Niveau moyen",`${fmt(s.moyenne)} cm`,C.blue);card(p,66,33,50,"Minimum",`${fmt(s.minimum)} cm`,C.green);card(p,120,33,50,"Maximum",`${fmt(s.maximum)} cm`,C.orange);card(p,174,33,50,"Stations suivies",String(s.stations.length),C.purple);card(p,228,33,57,"Territoire",terr,C.cyan);await map(p,checked,m,sp,151,68,134,58);ink(p,C.navy);p.setFont("helvetica","bold");p.setFontSize(8);p.text("À retenir pour la décision",12,70);ink(p,C.gray);p.setFont("helvetica","normal");p.setFontSize(6);p.text(p.splitTextToSize(`Sur ${terr}, le niveau moyen observé aux stations limnimétriques est de ${fmt(s.moyenne)} cm, avec un minimum de ${fmt(s.minimum)} cm et un maximum de ${fmt(s.maximum)} cm.`,132),12,79);table(p,["Station","Localité","Commune","Cours d’eau","Moyenne","Min","Max"],s.stations.map(x=>[x.code,x.localite,x.commune,x.cours_eau,`${fmt(x.moyenne)} cm`,`${fmt(x.minimum)} cm`,`${fmt(x.maximum)} cm`]),115)}
  footer(p);return new Response(p.output("arraybuffer"),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename=\"psore_${m}_rapport-decisionnel.pdf\"`}})}catch(e:any){console.error("PSORE safe pdf",e);return NextResponse.json({ok:false,error:e?.message||"Génération PDF impossible"},{status:500})}}
