"use client";
import{useEffect,useRef,useState}from"react";
declare global{interface Window{L:any}}
function esc(v:any){return String(v??"").replace(/[<>&"]/g,(c)=>({"<":"&lt;",">":"&gt;","&":"&amp;","\"":"&quot;"}[c] as string))}
export default function SigDecisionMap({stats,selectedId,onSelect}:{stats:any[];selectedId:any;onSelect:(id:any)=>void}){const ref=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),sbLayer=useRef<any>(null);const[status,setStatus]=useState("Chargement de la carte décisionnelle...");
 useEffect(()=>{let off=false;(async()=>{try{if(!document.getElementById("leaflet-css")){const l=document.createElement("link");l.id="leaflet-css";l.rel="stylesheet";l.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(l)}if(!window.L)await new Promise<void>((resolve,reject)=>{const e=document.getElementById("leaflet-js") as HTMLScriptElement|null;if(e){e.addEventListener("load",()=>resolve(),{once:true});e.addEventListener("error",()=>reject(new Error("Leaflet indisponible")),{once:true});return}const s=document.createElement("script");s.id="leaflet-js";s.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";s.onload=()=>resolve();s.onerror=()=>reject(new Error("Leaflet indisponible"));document.body.appendChild(s)});if(off||!ref.current)return;const L=window.L;const map=L.map(ref.current).setView([12.9,-7.55],9);mapRef.current=map;L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© contributeurs OpenStreetMap",maxZoom:18}).addTo(map);const [sb,rest,pz,mb]=await Promise.all([fetch("/data/decisionnel/sous_bassins.geojson").then(r=>r.json()),fetch("/data/decisionnel/restaurations.geojson").then(r=>r.json()),fetch("/data/referentiels/piezometres_reference.json").then(r=>r.json()),fetch("/data/referentiels/microbarrages_reference.json").then(r=>r.json())]);
 const byId=new Map(stats.map(x=>[String(x.id),x]));const color=(score:number)=>score>=70?"#C2413A":score>=45?"#D97706":score>=25?"#7C3AED":"#0F766E";const layer=L.geoJSON(sb,{style:(f:any)=>{const id=String(f?.properties?.HydroID??f?.properties?.OBJECTID??"");const st=byId.get(id);const sel=String(selectedId)===id;return{color:sel?"#071B33":"#0B4F80",weight:sel?4:1.4,fillColor:st?color(st.priorityScore):"#CBD5E1",fillOpacity:sel?.36:.18}},onEachFeature:(f:any,l:any)=>{const id=String(f?.properties?.HydroID??f?.properties?.OBJECTID??"");const st=byId.get(id);l.bindTooltip(`SB-${esc(id)}${st?` · priorité ${st.priorityScore}/100`:""}`);l.on("click",()=>onSelect(id))}}).addTo(map);sbLayer.current=layer;
 L.geoJSON(rest,{style:()=>({color:"#A16207",weight:.7,fillColor:"#F59E0B",fillOpacity:.18})}).addTo(map);const addPts=(arr:any[],color:string,label:string)=>{arr.forEach((x:any)=>{const lat=Number(x.latitude),lon=Number(x.longitude);if(Number.isFinite(lat)&&Number.isFinite(lon))L.circleMarker([lat,lon],{radius:5,color:"white",weight:1.5,fillColor:color,fillOpacity:.95}).bindPopup(`<strong>${label}</strong><br/>${esc(x.code||x.nom||x.village||"")}`).addTo(map)})};addPts(Array.isArray(pz)?pz:[],"#06B6D4","Piézomètre");addPts(Array.isArray(mb)?mb:(mb.data||[]),"#16A34A","Micro-barrage");try{map.fitBounds(layer.getBounds().pad(.05))}catch{}setStatus("Cliquez sur un sous-bassin pour afficher sa fiche analytique.")}catch(e:any){setStatus(`Carte indisponible : ${e?.message||"erreur"}`)}})();return()=>{off=true;try{mapRef.current?.remove()}catch{}mapRef.current=null}},[]);
 useEffect(()=>{const map=mapRef.current,layer=sbLayer.current;if(!map||!layer)return;layer.eachLayer((l:any)=>{const f=l.feature;const id=String(f?.properties?.HydroID??f?.properties?.OBJECTID??"");const st=stats.find(x=>String(x.id)===id);const sel=String(selectedId)===id;l.setStyle({color:sel?"#071B33":"#0B4F80",weight:sel?4:1.4,fillColor:st?(st.priorityScore>=70?"#C2413A":st.priorityScore>=45?"#D97706":st.priorityScore>=25?"#7C3AED":"#0F766E"):"#CBD5E1",fillOpacity:sel?.36:.18});if(sel){try{map.fitBounds(l.getBounds().pad(.35))}catch{}}})},[selectedId,stats]);
 return <div><div ref={ref} className="sig-decision-map"></div><div className="notice-empty">{status}</div></div>}
