"use client";
import { useEffect, useMemo, useState } from "react";
import restorations from "@/public/data/decisionnel/restaurations_resume.json";
import microbarrages from "@/public/data/referentiels/microbarrages_reference.json";
import forages from "@/public/data/referentiels/forages_exploitation_crr_pm.json";
import piezos from "@/public/data/referentiels/piezometres_reference.json";
import sousBassins from "@/public/data/decisionnel/sous_bassins_data.json";
import restaurationsGeo from "@/public/data/decisionnel/restaurations_data.json";
import { classifyPiezoEvolution, normalizeLocality } from "@/lib/piezo-reference";

function n(v:any){const x=Number(v);return Number.isFinite(x)?x:0}
function numeric(v:any){if(v===null||v===undefined||v==="")return null;const x=Number(String(v).replace(",","."));return Number.isFinite(x)?x:null}
function format(x:number,d=0){return x.toLocaleString("fr-FR",{maximumFractionDigits:d})}
function val(r:any,...keys:string[]){for(const k of keys){if(r?.[k]!==undefined&&r?.[k]!==null&&r?.[k]!=="")return r[k]}return null}
function dateOf(r:any){return String(val(r,"date_observation","date_mesure","date")||"")}
function centroid(g:any){const pts:any[]=[];const walk=(x:any)=>{if(Array.isArray(x)&&typeof x[0]==="number")pts.push(x);else if(Array.isArray(x))x.forEach(walk)};walk(g?.coordinates);if(!pts.length)return null;return[pts.reduce((s,p)=>s+p[0],0)/pts.length,pts.reduce((s,p)=>s+p[1],0)/pts.length]}
function inRing(pt:any,ring:any[]){let c=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if(((a[1]>pt[1])!==(b[1]>pt[1]))&&(pt[0]<(b[0]-a[0])*(pt[1]-a[1])/(b[1]-a[1]||1e-12)+a[0]))c=!c}return c}
function inside(pt:any,geom:any){if(!pt||!geom)return false;if(geom.type==="Polygon")return inRing(pt,geom.coordinates?.[0]||[]);if(geom.type==="MultiPolygon")return (geom.coordinates||[]).some((p:any)=>inRing(pt,p?.[0]||[]));return false}
function mean(rows:any[],key:string){const xs=rows.map(r=>numeric(r[key]??r.valeur_observee)).filter((x):x is number=>x!==null);return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null}
function pearson(xs:number[],ys:number[]){if(xs.length<3||xs.length!==ys.length)return null;const mx=xs.reduce((a,b)=>a+b,0)/xs.length,my=ys.reduce((a,b)=>a+b,0)/ys.length;let num=0,dx=0,dy=0;for(let i=0;i<xs.length;i++){const a=xs[i]-mx,b=ys[i]-my;num+=a*b;dx+=a*a;dy+=b*b}return dx&&dy?num/Math.sqrt(dx*dy):null}
function clamp01(x:number){return Math.max(0,Math.min(1,x))}
function confidence(x:any){let score=0;if(x.comparables>0)score+=40;if(x.rainCount>0)score+=20;if(x.limniCount>0)score+=15;if(x.restorations>0)score+=15;if(x.microbarrages>0)score+=10;return score>=80?"Robuste":score>=55?"Modérée":score>=30?"Faible":"Données insuffisantes"}

export default function SigDecisionnelDashboard(){
  const [surfaceScenario,setSurfaceScenario]=useState(500);const [rayon,setRayon]=useState(2000);const [piezoRows,setPiezoRows]=useState<any[]>([]);const [pluvioRows,setPluvioRows]=useState<any[]>([]);const [limniRows,setLimniRows]=useState<any[]>([]);const [liveError,setLiveError]=useState("");const [selected,setSelected]=useState("restauration");
  const data:any=restorations;const micro:any[]=Array.isArray(microbarrages)?microbarrages:(microbarrages as any).data||[];const fs:any[]=Array.isArray(forages)?forages:(forages as any).data||[];const pz:any[]=Array.isArray(piezos)?piezos:(piezos as any).data||[];
  useEffect(()=>{Promise.all(["piezometrie","pluviometrie","limnimetrie"].map(m=>fetch(`/api/dashboard/module?module=${m}`,{cache:"no-store"}).then(r=>r.json()))).then(([pi,pl,li])=>{setPiezoRows(Array.isArray(pi?.data)?pi.data:[]);setPluvioRows(Array.isArray(pl?.data)?pl.data:[]);setLimniRows(Array.isArray(li?.data)?li.data:[])}).catch(e=>setLiveError(e?.message||"Données actuelles indisponibles"))},[]);
  const technologies=useMemo(()=>Object.entries((data as any).technologies||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1])),[data]);const communes=useMemo(()=>Object.entries((data as any).communes||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1])),[data]);const currentSurface=n((data as any).surface_ha);const projected=currentSurface+n(surfaceScenario);
  const piezoComparison=useMemo(()=>pz.map((ref:any)=>{const key=normalizeLocality(ref.village);const matches=piezoRows.filter(r=>normalizeLocality(val(r,"nom_site","village","localite","site","code_site"))===key).sort((a,b)=>dateOf(b).localeCompare(dateOf(a)));const latest=matches[0]||null;const current=latest?numeric(val(latest,"niveau_statique","valeur_observee")):null;return {...ref,current,date_current:latest?dateOf(latest):null,...classifyPiezoEvolution(ref.niveau_statique_m,current)}}),[pz,piezoRows]);
  const comparable=piezoComparison.filter(x=>x.current!==null);const meanDelta=comparable.length?comparable.reduce((s,x)=>s+Number(x.delta||0),0)/comparable.length:null;const trends=piezoComparison.reduce((a:any,x:any)=>{a[x.status]=(a[x.status]||0)+1;return a},{});
  const subbasinStats=useMemo(()=>{const sb:any[]=(sousBassins as any).features||[],rr:any[]=(restaurationsGeo as any).features||[];return sb.map((b:any)=>{const restor=rr.filter((r:any)=>inside(centroid(r.geometry),b.geometry));const area=restor.reduce((sum:number,r:any)=>sum+n(r.properties?.Surf_ha),0);const basinHa=n(b.properties?.Shape_Area)/10000;const density=basinHa?area/basinHa*100:0;const refs=pz.filter((r:any)=>inside([Number(r.longitude),Number(r.latitude)],b.geometry));const live=piezoComparison.filter((r:any)=>refs.some((x:any)=>x.code===r.code)&&r.current!==null);const delta=live.length?live.reduce((sum:number,r:any)=>sum+Number(r.delta||0),0)/live.length:null;const rain=pluvioRows.filter((r:any)=>inside([Number(r.longitude),Number(r.latitude)],b.geometry));const limni=limniRows.filter((r:any)=>inside([Number(r.longitude),Number(r.latitude)],b.geometry));const mb=micro.filter((r:any)=>inside([Number(r.longitude),Number(r.latitude)],b.geometry));const rainAvg=mean(rain,"pluie_24h_mm"),limniAvg=mean(limni,"hauteur_eau");const restorationGap=1-clamp01(density/5);const stress=delta===null?0:clamp01(Math.max(0,delta)/5);const monitorGap=refs.length?0:1;const priorityScore=Math.round((0.45*restorationGap+0.35*stress+0.20*monitorGap)*100);return{id:b.properties?.HydroID??b.properties?.OBJECTID,basinHa,area,density,restorations:restor.length,piezos:refs.length,comparables:live.length,delta,rainCount:rain.length,rainAvg,limniCount:limni.length,limniAvg,microbarrages:mb.length,priorityScore,confidence:""}}).map(x=>({...x,confidence:confidence(x)})).filter(x=>x.restorations||x.piezos||x.rainCount||x.limniCount||x.microbarrages).sort((a,b)=>b.priorityScore-a.priorityScore)},[piezoComparison,pz,pluvioRows,limniRows,micro]);
  const allocation=useMemo(()=>{const eligible=subbasinStats.filter(x=>x.priorityScore>0).slice(0,12);const total=eligible.reduce((s,x)=>s+x.priorityScore,0)||1;return eligible.map(x=>({...x,allocation:surfaceScenario*x.priorityScore/total})).sort((a,b)=>b.allocation-a.allocation)},[subbasinStats,surfaceScenario]);
  const correlation=useMemo(()=>{const x=subbasinStats.filter(s=>s.delta!==null);return pearson(x.map(s=>s.density),x.map(s=>Number(s.delta)))},[subbasinStats]);
  const monitoredRestored=subbasinStats.filter(x=>x.restorations>0&&x.piezos>0);const gaps=subbasinStats.filter(x=>x.restorations>0&&x.piezos===0).sort((a,b)=>b.area-a.area);const mbComparable=subbasinStats.filter(x=>x.microbarrages>0&&x.delta!==null);const mbDelta=mbComparable.length?mbComparable.reduce((s,x)=>s+Number(x.delta),0)/mbComparable.length:null;
  const scenario:any={
    restauration:{title:"Restauration ciblée",metric:`${format(surfaceScenario)} ha simulés`,text:`Allocation indicative vers les sous-bassins combinant faible densité de restauration, signal de baisse piézométrique et déficit de suivi. Premier sous-bassin : ${allocation[0]?`SB-${allocation[0].id} (${format(allocation[0].allocation,1)} ha)`:"données insuffisantes"}.`},
    monitoring:{title:"Renforcement du réseau de suivi",metric:`${gaps.length} sous-bassin(s)`,text:`Sous-bassins restaurés sans piézomètre de référence. Priorité de suivi : ${gaps.slice(0,3).map(x=>`SB-${x.id}`).join(", ")||"aucune lacune détectée"}.`},
    impact:{title:"Association restauration–nappe",metric:correlation===null?"Non calculable":`r = ${format(correlation,2)}`,text:correlation===null?"Moins de trois sous-bassins disposent de couples comparables densité de restauration / variation piézométrique.":`Corrélation descriptive sur les sous-bassins comparables. ${Math.abs(correlation)<0.3?"Association faible":Math.abs(correlation)<0.6?"Association modérée":"Association marquée"}; aucune causalité n'est déduite automatiquement.`},
    barrages:{title:"Micro-barrages + restauration",metric:`${mbComparable.length} sous-bassin(s) comparables`,text:mbDelta===null?"Aucun sous-bassin avec micro-barrage ne dispose encore d'une mesure piézométrique comparable.":`Écart piézométrique moyen dans les sous-bassins contenant un micro-barrage : ${mbDelta>0?"+":""}${format(mbDelta,2)} m. À contrôler par la pluie, la saison et les prélèvements.`},
    compare:{title:"Comparaison inter-sous-bassins",metric:`${monitoredRestored.length} unités suivies`,text:`Comparaison des densités de restauration, pluie disponible, réponse piézométrique et limnimétrique. Les niveaux de confiance dépendent de la couverture des différents réseaux.`}
  };
  const sc=scenario[selected];
  return <div className="integrated-observatory">
    <section className="panel"><h2>Lecture territoriale intégrée</h2><p>Analyse dynamique des restaurations, des 4 micro-barrages réhabilités, des forages d’exploitation et des réseaux de suivi. Les résultats sont recalculés avec les mesures synchronisées disponibles.</p>{liveError&&<div className="alert warn">{liveError}</div>}<div className="sig-decision-grid"><article><small>Surface restaurée</small><b>{format(currentSurface,1)} ha</b><span>{format(n((data as any).sites))} sites/parcelles</span></article><article><small>PZ comparables</small><b>{comparable.length}/20</b><span>mesure actuelle vs référence</span></article><article><small>Écart moyen NS</small><b>{meanDelta===null?"—":`${meanDelta>0?"+":""}${format(meanDelta,2)} m`}</b><span>positif = nappe plus profonde</span></article><article><small>Sous-bassins analysés</small><b>{subbasinStats.length}</b><span>avec au moins une donnée utile</span></article></div></section>
    <section className="panel"><h2>Analyse hydrique dynamique par sous-bassin</h2><p>Chaque sous-bassin croise superficie restaurée, densité de restauration, PZ, pluie, limnimétrie et micro-barrages. Le score de priorité sert uniquement à hiérarchiser les investigations et interventions.</p><div className="table-wrap"><table className="table"><thead><tr><th>Sous-bassin</th><th>Surface SB</th><th>Restauré</th><th>Densité</th><th>PZ comp.</th><th>Δ NS</th><th>Pluie moy.</th><th>Limni moy.</th><th>Micro-barrages</th><th>Priorité</th><th>Confiance</th></tr></thead><tbody>{subbasinStats.slice(0,50).map((x:any)=><tr key={x.id}><td><strong>SB-{x.id}</strong></td><td>{format(x.basinHa,0)} ha</td><td>{format(x.area,1)} ha</td><td>{format(x.density,2)}%</td><td>{x.comparables}/{x.piezos}</td><td>{x.delta===null?"—":`${x.delta>0?"+":""}${format(x.delta,2)} m`}</td><td>{x.rainAvg===null?"—":`${format(x.rainAvg,1)} mm`}</td><td>{x.limniAvg===null?"—":format(x.limniAvg,1)}</td><td>{x.microbarrages}</td><td><strong>{x.priorityScore}/100</strong></td><td>{x.confidence}</td></tr>)}</tbody></table></div></section>
    <section className="panel"><h2>Scénarios d’aide à la décision — calculés sur les données disponibles</h2><div className="filters-grid"><label>Surface additionnelle à restaurer (ha)<input className="input" type="number" min="0" step="50" value={surfaceScenario} onChange={e=>setSurfaceScenario(Number(e.target.value)||0)}/></label><label>Rayon analytique de proximité<input className="input" type="number" min="250" step="250" value={rayon} onChange={e=>setRayon(Number(e.target.value)||0)}/></label></div><div className="quick-actions" style={{marginTop:14}}>{Object.entries(scenario).map(([k,v]:any)=><button key={k} className={selected===k?"btn btn-primary":"btn btn-soft"} onClick={()=>setSelected(k)}>{v.title}</button>)}</div><div className="panel" style={{marginTop:16,background:"#f7fbff"}}><h3>{sc.title}</h3><div className="sig-decision-grid"><article><small>Résultat calculé</small><b>{sc.metric}</b></article><article><small>Surface projetée globale</small><b>{format(projected,1)} ha</b></article><article><small>Hausse / stable</small><b>{trends.Hausse||0} / {trends.Stable||0}</b></article><article><small>Baisse</small><b>{trends.Baisse||0}</b></article></div><p style={{marginTop:12}}>{sc.text}</p>{selected==="restauration"&&<div className="table-wrap"><table className="table"><thead><tr><th>Rang</th><th>Sous-bassin</th><th>Score</th><th>Allocation indicative</th><th>Densité actuelle</th><th>Δ NS</th><th>Confiance</th></tr></thead><tbody>{allocation.slice(0,10).map((x:any,i)=><tr key={x.id}><td>{i+1}</td><td>SB-{x.id}</td><td>{x.priorityScore}/100</td><td>{format(x.allocation,1)} ha</td><td>{format(x.density,2)}%</td><td>{x.delta===null?"—":`${x.delta>0?"+":""}${format(x.delta,2)} m`}</td><td>{x.confidence}</td></tr>)}</tbody></table></div>}</div><p className="decision-note">Les scénarios sont des outils de priorisation et de comparaison. Les associations spatiales ou temporelles doivent être confirmées par l’analyse hydrologique/hydrogéologique, notamment en contrôlant pluie, saison, prélèvements et ancienneté des interventions.</p></section>
    <div className="sig-two-col"><section className="panel"><h2>Technologies de restauration</h2><ol className="sig-ranking">{technologies.slice(0,10).map(([k,v]:any)=><li key={String(k)}><strong>{String(k)}</strong> — {format(Number(v))} site(s)</li>)}</ol></section><section className="panel"><h2>Répartition communale</h2><ol className="sig-ranking">{communes.map(([k,v]:any)=><li key={String(k)}><strong>{String(k)}</strong> — {format(Number(v))} site(s)</li>)}</ol></section></div>
  </div>;
}
