-- PSORE V4.0 — Observatoire intégré des ouvrages
-- À exécuter après database/00_migration_complete_v2_4.sql

create extension if not exists pgcrypto;

create table if not exists public.forages_exploitation (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  composante text not null check (composante in ('CRR','PM')),
  commune text not null,
  site text not null,
  forage text not null,
  x_utm double precision,
  y_utm double precision,
  epsg integer default 32629,
  longitude double precision,
  latitude double precision,
  etat text default 'POSITIF',
  hmt_m double precision,
  cote_installation_pompe_m double precision,
  debit_exploitation_m3h double precision,
  marque_pompe text,
  puissance_pompe_kw double precision,
  nombre_modules integer,
  puissance_module_w double precision,
  puissance_installee_kwc double precision,
  entreprise text,
  numero_compteur text,
  date_mise_service date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.releves_prelevements (
  id uuid primary key default gen_random_uuid(),
  forage_id uuid not null references public.forages_exploitation(id) on delete cascade,
  date_releve date not null,
  index_compteur_m3 double precision,
  index_precedent_m3 double precision,
  volume_periode_m3 double precision,
  heures_pompage double precision,
  debit_observe_m3h double precision,
  niveau_statique_m double precision,
  niveau_dynamique_m double precision,
  usage text,
  incident text,
  observateur text,
  created_at timestamptz default now(),
  unique(forage_id,date_releve)
);

create table if not exists public.essais_pompage_piezometres (
  id uuid primary key default gen_random_uuid(),
  code_piezo text unique not null,
  site text not null,
  forage text,
  date_essai date,
  profondeur_totale_m double precision,
  profondeur_tubee_m double precision,
  crepine_superieure_m double precision,
  venue_eau_principale_m double precision,
  epaisseur_alterites_m double precision,
  niveau_statique_m double precision,
  debit_developpement_m3h double precision,
  debit_palier_1_m3h double precision,
  debit_palier_2_m3h double precision,
  debit_palier_3_m3h double precision,
  niveau_etiage_estime_m double precision,
  niveau_dynamique_max_m double precision,
  rabattement_max_m double precision,
  created_at timestamptz default now()
);

create table if not exists public.analyses_eau_piezometres (
  id uuid primary key default gen_random_uuid(),
  code_piezo text not null,
  site text not null,
  date_prelevement date,
  laboratoire text,
  ph double precision,
  conductivite_us_cm double precision,
  temperature_c double precision,
  turbidite_ntu double precision,
  tds_mg_l double precision,
  nitrates_mg_l double precision,
  nitrites_mg_l double precision,
  ammonium_mg_l double precision,
  chlorures_mg_l double precision,
  sulfates_mg_l double precision,
  fluorures_mg_l double precision,
  fer_mg_l double precision,
  manganese_mg_l double precision,
  coliformes_ufc_100ml double precision,
  e_coli_ufc_100ml double precision,
  conclusion_laboratoire text,
  document_source text,
  statut_validation text default 'A_SAISIR',
  created_at timestamptz default now()
);

create index if not exists idx_forages_exploitation_composante on public.forages_exploitation(composante);
create index if not exists idx_forages_exploitation_commune on public.forages_exploitation(commune);
create index if not exists idx_releves_prelevements_date on public.releves_prelevements(date_releve);
create index if not exists idx_analyses_eau_code on public.analyses_eau_piezometres(code_piezo);

alter table public.forages_exploitation enable row level security;
alter table public.releves_prelevements enable row level security;
alter table public.essais_pompage_piezometres enable row level security;
alter table public.analyses_eau_piezometres enable row level security;

drop policy if exists "lecture authentifiee forages exploitation" on public.forages_exploitation;
create policy "lecture authentifiee forages exploitation" on public.forages_exploitation for select to authenticated using (true);
drop policy if exists "lecture authentifiee essais piezo" on public.essais_pompage_piezometres;
create policy "lecture authentifiee essais piezo" on public.essais_pompage_piezometres for select to authenticated using (true);
drop policy if exists "lecture authentifiee analyses piezo" on public.analyses_eau_piezometres;
create policy "lecture authentifiee analyses piezo" on public.analyses_eau_piezometres for select to authenticated using (true);
drop policy if exists "gestion authentifiee prelevements" on public.releves_prelevements;
create policy "gestion authentifiee prelevements" on public.releves_prelevements for all to authenticated using (true) with check (true);

insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('CRR-DOUMBA-F1','CRR','Doumba','Doumba','F1',652492,1450244,32629,-7.5932626,13.1146924,'POSITIF',137,127,8.0,'GRUNDFOS',4.0,18,550,9.9,'ENCA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('CRR-DOUMBA-F3','CRR','Doumba','Doumba','F3',652492,1450348,32629,-7.5932573,13.1156325,'POSITIF',77,67,6.0,'LORENTZ',2.5,8,550,4.4,'ENCA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('CRR-KEKAN-F1','CRR','Méguétan','Kékan','F1',660183,1424340,32629,-7.5237142,12.8801309,'POSITIF',30,20,20.0,'LORENTZ',1.5,8,550,4.4,'ENCA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('CRR-KEKAN-F2','CRR','Méguétan','Kékan','F2',660361,1424343,32629,-7.5220739,12.8801488,'POSITIF',30,20,13.0,'LORENTZ',1.5,8,550,4.4,'ENCA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('CRR-KOULA-F2','CRR','Koula','Koula','F2',646547,1449123,32629,-7.6481495,13.104852,'POSITIF',50,40,13.0,'LORENTZ',1.5,8,550,4.4,'ENCA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('CRR-KOULA-F4','CRR','Koula','Koula','F4',646564,1449046,32629,-7.6479966,13.1041551,'POSITIF',45,35,10.0,'LORENTZ',1.5,8,550,4.4,'ENCA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('CRR-SIRAKOROLA-F1','CRR','Sirakorola','Sirakorola','F1',655918,1469701,32629,-7.5606349,13.2904034,'POSITIF',115,105,4.0,'GRUNDFOS',2.5,12,550,6.6,'ENCA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('CRR-SIRAKOROLA-F2','CRR','Sirakorola','Sirakorola','F2',655950,1469625,32629,-7.5603436,13.2897148,'POSITIF',35,25,11.0,'LORENTZ',1.5,8,550,4.4,'ENCA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('PM-KENEKELE-F1','PM','Doumba','Kénékélé','F1',652623,1444238,32629,-7.5923626,13.0603921,'POSITIF',53,38,7.0,'AC/DC',NULL,8,550,4.4,'SEEBA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('PM-KENEKELE-F3','PM','Doumba','Kénékélé','F3',652586,1444232,32629,-7.5927041,13.0603397,'POSITIF',63,48,5.5,'AC/DC',NULL,8,550,4.4,'SEEBA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('PM-NADIOBOUGOU-F1','PM','Doumba','Nadiobougou','F1',649882,1446471,32629,-7.6175252,13.0807148,'POSITIF',114,99,6.5,'AC/DC',NULL,12,550,6.6,'SEEBA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('PM-NADIOBOUGOU-F2','PM','Doumba','Nadiobougou','F2',649998,1446409,32629,-7.6164586,13.0801486,'POSITIF',121,106,10.0,'AC/DC',NULL,12,550,6.6,'SEEBA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('PM-BABOUGOU-F1','PM','Doumba','Babougou','F1',655025,1454539,32629,-7.569676,13.1533896,'POSITIF',93,78,11.5,'AC/DC',NULL,12,550,6.6,'SEEBA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('PM-BABOUGOU-F2','PM','Doumba','Babougou','F2',654992,1454541,32629,-7.5699803,13.1534094,'POSITIF',89,74,16.0,'AC/DC',NULL,12,550,6.6,'SEEBA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('PM-MONZONA-F1','PM','Koula','Monzona','F1',668892,1457385,32629,-7.4416028,13.1783712,'POSITIF',69,54,4.2,'AC/DC',NULL,8,555,4.44,'SEEBA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.forages_exploitation (code,composante,commune,site,forage,x_utm,y_utm,epsg,longitude,latitude,etat,hmt_m,cote_installation_pompe_m,debit_exploitation_m3h,marque_pompe,puissance_pompe_kw,nombre_modules,puissance_module_w,puissance_installee_kwc,entreprise) values ('PM-MONZONA-F3','PM','Koula','Monzona','F3',668976,1457342,32629,-7.4408304,13.1779778,'POSITIF',49,34,21.0,'AC/DC',NULL,12,550,6.6,'SEEBA-Sarl') on conflict (code) do update set composante=excluded.composante,commune=excluded.commune,site=excluded.site,forage=excluded.forage,x_utm=excluded.x_utm,y_utm=excluded.y_utm,epsg=excluded.epsg,longitude=excluded.longitude,latitude=excluded.latitude,etat=excluded.etat,hmt_m=excluded.hmt_m,cote_installation_pompe_m=excluded.cote_installation_pompe_m,debit_exploitation_m3h=excluded.debit_exploitation_m3h,marque_pompe=excluded.marque_pompe,puissance_pompe_kw=excluded.puissance_pompe_kw,nombre_modules=excluded.nombre_modules,puissance_module_w=excluded.puissance_module_w,puissance_installee_kwc=excluded.puissance_installee_kwc,entreprise=excluded.entreprise;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-12','Boron Cissé','F1','23/04/2025',10.9,5.6,10.2,12.8,40.3,39.16,20.7,34.0,17.0,20.0,12.08,20.7,8.62) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-18','Diaguinébougou','F1','28/04/2025',6.8,3.0,4.1,5.1,78.0,78.0,54.83,70.0,12.0,7.4,8.21,54.83,46.62) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-04','Dialakorobougou','F1','24/04/2025',6.81,2.3,5.2,8.2,100.0,100.0,55.0,59.0,21.0,6.0,8.31,55.0,46.69) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-20','Diladjè','F1','27/04/2025',8.8,1.6,2.5,3.0,61.1,60.07,38.7,54.0,24.3,3.6,10.08,38.7,28.62) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-11','Dlana','F1','22/04/2025',11.17,6.1,10.7,13.0,45.8,44.11,34.38,36.0,19.0,17.0,12.35,34.38,22.03) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-02','Dombana','F2','26/04/2025',8.84,3.6,7.3,12.0,35.3,34.2,27.88,29.0,20.0,15.2,10.13,27.88,17.75) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-13','Dontérébougou','F1','21/04/2025',9.83,6.0,9.4,12.8,48.1,47.03,40.7,42.0,32.5,27.0,11.14,40.7,29.56) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-03','Doumba','F1','26/04/2025',8.69,0.5,1.1,1.4,87.5,87.5,68.0,70.0,21.0,1.4,9.99,68.0,58.01) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-01','Fani','F1','24/04/2025',3.25,5.4,10.3,14.3,37.0,36.0,27.24,35.0,17.0,36.0,5.04,27.24,22.2) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-07','Félou','F1','18/05/2025',10.86,1.1,3.2,4.9,91.1,91.1,59.66,63.0,20.06,4.1,11.6,59.66,48.06) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-17','Fégoun','F1','28/04/2025',12.18,1.7,3.6,5.9,46.0,46.0,28.65,37.0,6.0,6.3,13.17,28.65,15.48) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-16','Gouni','F1','29/04/2025',7.4,0.9,1.3,2.2,82.0,82.0,55.9,63.0,8.0,2.8,8.74,55.9,47.16) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-14','Koroka','F1','21/04/2025',15.34,1.5,3.4,7.5,86.1,84.82,25.62,54.0,28.0,10.0,16.17,25.62,9.45) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-10','Monzombala','F1','22/04/2025',14.73,3.0,9.4,12.0,61.1,59.91,44.35,54.0,21.0,15.0,15.6,44.35,28.75) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-06','Gnamakorobougou','F1','26/04/2025',5.82,2.5,6.8,10.7,71.1,70.05,55.0,67.0,21.3,10.8,7.35,55.0,47.65) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-08','Niobougou','F1','17/05/2025',14.73,1.8,2.8,4.6,66.1,66.1,28.92,46.0,19.84,4.5,15.28,28.92,13.64) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-09','Sirakorola Ouest','F1','20/04/2025',10.18,3.57,7.9,15.0,80.0,79.98,58.61,59.0,10.0,15.0,11.48,58.61,47.13) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-19','Siratiguila','F1','29/04/2025',14.63,1.0,1.9,3.0,78.0,78.0,28.64,35.0,6.0,3.4,15.42,28.64,13.22) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-05','Wolokorodji','F1','25/04/2025',11.83,1.6,2.7,3.0,81.0,80.02,52.83,57.0,19.5,3.1,12.9,52.83,39.93) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.essais_pompage_piezometres (code_piezo,site,forage,date_essai,niveau_statique_m,q1_m3h,q2_m3h,q3_m3h,profondeur_totale_m,profondeur_tubee_m,crepine_sup_m,venue_eau_principale_m,epaisseur_alterites_m,debit_developpement_m3h,niveau_etiage_m,niveau_dynamique_max_m,rabattement_max_m) values ('PZ-15','Zana','F1','21/04/2025',5.87,2.1,4.4,6.5,61.1,60.0,47.36,49.0,7.66,9.0,7.52,47.36,39.84) on conflict (code_piezo) do update set site=excluded.site,forage=excluded.forage,date_essai=excluded.date_essai,niveau_statique_m=excluded.niveau_statique_m,q1_m3h=excluded.q1_m3h,q2_m3h=excluded.q2_m3h,q3_m3h=excluded.q3_m3h,profondeur_totale_m=excluded.profondeur_totale_m,profondeur_tubee_m=excluded.profondeur_tubee_m,crepine_sup_m=excluded.crepine_sup_m,venue_eau_principale_m=excluded.venue_eau_principale_m,epaisseur_alterites_m=excluded.epaisseur_alterites_m,debit_developpement_m3h=excluded.debit_developpement_m3h,niveau_etiage_m=excluded.niveau_etiage_m,niveau_dynamique_max_m=excluded.niveau_dynamique_max_m,rabattement_max_m=excluded.rabattement_max_m;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-01','Fani','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-02','Dombana','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-03','Doumba','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-04','Dialakorobougou','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-05','Wolokorodji','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-06','Gnamakorobougou','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-07','Félou','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-08','Niobougou','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-09','Sirakorola Ouest','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-10','Monzombala','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-11','Dlana','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-12','Boron Cissé','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-13','Dontérébougou','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-14','Koroka','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-15','Zana','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-16','Gouni','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-17','Fégoun','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-18','Diaguinébougou','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-19','Siratiguila','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;
insert into public.analyses_eau_piezometres (code_piezo,site,document_source,statut_validation) values ('PZ-20','Diladjè','Archives analyses d''eau des piézomètres','A_SAISIR') on conflict do nothing;

create or replace view public.v_forages_exploitation_suivi as
select f.*,
       max(r.date_releve) as derniere_date_releve,
       max(r.index_compteur_m3) filter (where r.date_releve = (select max(r2.date_releve) from public.releves_prelevements r2 where r2.forage_id=f.id)) as dernier_index_compteur_m3,
       coalesce(sum(r.volume_periode_m3),0) as volume_total_releve_m3
from public.forages_exploitation f
left join public.releves_prelevements r on r.forage_id=f.id
group by f.id;

comment on table public.forages_exploitation is 'Référentiel des 16 forages d’exploitation CRR et PM';
comment on table public.releves_prelevements is 'Relevés périodiques des compteurs et niveaux des forages exploités';
comment on table public.essais_pompage_piezometres is 'Résultats initiaux des essais de pompage des 20 piézomètres';
comment on table public.analyses_eau_piezometres is 'Résultats physico-chimiques et bactériologiques des piézomètres';
