-- PSORE V4.5.0 — synchronisation Epicollect5 parent/enfant + robustesse des données
-- À exécuter UNE FOIS avant la première synchronisation V4.5.

begin;

alter table if exists public.observations_pluvio add column if not exists source_parent_id text;
alter table if exists public.observations_pluvio add column if not exists raw_payload jsonb;
alter table if exists public.observations_piezo add column if not exists source_parent_id text;
alter table if exists public.observations_piezo add column if not exists raw_payload jsonb;
alter table if exists public.observations_limni add column if not exists source_parent_id text;
alter table if exists public.observations_limni add column if not exists raw_payload jsonb;
alter table if exists public.points_eau add column if not exists raw_payload jsonb;

create index if not exists observations_pluvio_parent_idx on public.observations_pluvio(source_parent_id);
create index if not exists observations_piezo_parent_idx on public.observations_piezo(source_parent_id);
create index if not exists observations_limni_parent_idx on public.observations_limni(source_parent_id);
create index if not exists stations_pluvio_source_idx on public.stations_pluvio(source_entry_id);
create index if not exists piezometres_source_idx on public.piezometres(source_entry_id);
create index if not exists stations_limni_source_idx on public.stations_limni(source_entry_id);

create table if not exists public.sync_rejects (
  id bigint generated by default as identity primary key,
  module text not null,
  source text not null,
  target_table text,
  source_entry_id text,
  reason text not null,
  raw_payload jsonb,
  created_at timestamptz not null default now()
);
create index if not exists sync_rejects_module_source_idx on public.sync_rejects(module,source,created_at desc);
alter table public.sync_rejects enable row level security;

-- Les observations enfants sont rattachées au formulaire parent par parent_uuid.
create or replace view public.v_pluviometrie_dashboard as
select
  o.id,o.date_observation,
  coalesce(s.code_station,o.code_station) as code_site,
  coalesce(s.nom_station,s.village,o.code_station) as nom_site,
  coalesce(s.commune,c.nom) as commune,
  s.latitude,s.longitude,
  o.pluie_24h_mm as valeur_observee,o.pluie_24h_mm,o.cumul_mensuel_mm,
  o.observateur,o.commentaire,o.photo_url,o.source_parent_id,o.synced_at,
  case when o.pluie_24h_mm is null or o.pluie_24h_mm < 0 or o.pluie_24h_mm > 300 then true else false end as alerte_valeur,
  case when s.latitude is null or s.longitude is null then true else false end as alerte_gps,
  case when o.date_observation is null or o.pluie_24h_mm is null then true else false end as alerte_donnee
from public.observations_pluvio o
left join public.stations_pluvio s on
  o.station_id=s.id
  or (o.code_station is not null and o.code_station=s.code_station)
  or (o.source_parent_id is not null and o.source_parent_id=s.source_entry_id)
left join public.communes c on s.commune_id=c.id
where o.date_observation is not null and o.pluie_24h_mm is not null;

create or replace view public.v_piezometrie_dashboard as
select
  o.id,o.date_observation,
  coalesce(p.code_piezo,o.code_piezo) as code_site,
  coalesce(p.localite,p.village,p.code_piezo,o.code_piezo) as nom_site,
  coalesce(p.commune,c.nom) as commune,
  p.latitude,p.longitude,
  o.niveau_statique as valeur_observee,o.niveau_statique,p.profondeur,p.aquifere,
  o.observateur,o.commentaire,o.photo_url,o.source_parent_id,o.synced_at,
  case when o.niveau_statique is null or o.niveau_statique < 0 or (p.profondeur is not null and o.niveau_statique > p.profondeur) then true else false end as alerte_valeur,
  case when p.latitude is null or p.longitude is null then true else false end as alerte_gps,
  case when o.date_observation is null or o.niveau_statique is null then true else false end as alerte_donnee
from public.observations_piezo o
left join public.piezometres p on
  o.piezometre_id=p.id
  or (o.code_piezo is not null and o.code_piezo=p.code_piezo)
  or (o.source_parent_id is not null and o.source_parent_id=p.source_entry_id)
left join public.communes c on p.commune_id=c.id
where o.date_observation is not null and o.niveau_statique is not null;

create or replace view public.v_limnimetrie_dashboard as
select
  o.id,o.date_observation,
  coalesce(s.code_station,o.code_station) as code_site,
  coalesce(s.localite,s.village,s.cours_eau,o.code_station) as nom_site,
  coalesce(s.commune,c.nom) as commune,
  s.latitude,s.longitude,
  o.hauteur_eau as valeur_observee,o.hauteur_eau,o.periode,
  o.observateur,o.commentaire,o.photo_url,o.source_parent_id,o.synced_at,
  case when o.hauteur_eau is null or o.hauteur_eau < 0 then true else false end as alerte_valeur,
  case when s.latitude is null or s.longitude is null then true else false end as alerte_gps,
  case when o.date_observation is null or o.hauteur_eau is null then true else false end as alerte_donnee
from public.observations_limni o
left join public.stations_limni s on
  o.station_id=s.id
  or (o.code_station is not null and o.code_station=s.code_station)
  or (o.source_parent_id is not null and o.source_parent_id=s.source_entry_id)
left join public.communes c on s.commune_id=c.id
where o.date_observation is not null and o.hauteur_eau is not null;

-- Nettoyage des rejets très anciens pour éviter une croissance sans limite (conservation 90 jours).
delete from public.sync_rejects where created_at < now() - interval '90 days';

commit;
