-- PSORE V4.5.1 — correctif robuste synchronisation parent/enfant
-- Ce script remplace l'exécution défaillante de 19_sync_child_forms_v4_5.sql.
-- Il peut être exécuté même si le script 19 a échoué : aucun renommage de vue existante n'est tenté.

begin;

alter table if exists public.observations_pluvio add column if not exists source_parent_id text;
alter table if exists public.observations_pluvio add column if not exists raw_payload jsonb;
alter table if exists public.observations_piezo add column if not exists source_parent_id text;
alter table if exists public.observations_piezo add column if not exists raw_payload jsonb;
alter table if exists public.observations_limni add column if not exists source_parent_id text;
alter table if exists public.observations_limni add column if not exists raw_payload jsonb;
alter table if exists public.points_eau add column if not exists raw_payload jsonb;

create index if not exists observations_pluvio_parent_idx on public.observations_pluvio(source_parent_id);
create index if not exists observations_piezo_parent_idx on public.observations_piezo(source_parent_id);
create index if not exists observations_limni_parent_idx on public.observations_limni(source_parent_id);
create index if not exists stations_pluvio_source_idx on public.stations_pluvio(source_entry_id);
create index if not exists piezometres_source_idx on public.piezometres(source_entry_id);
create index if not exists stations_limni_source_idx on public.stations_limni(source_entry_id);

create table if not exists public.sync_rejects (
  id bigint generated by default as identity primary key,
  module text not null,
  source text not null,
  target_table text,
  source_entry_id text,
  reason text not null,
  raw_payload jsonb,
  created_at timestamptz not null default now()
);
create index if not exists sync_rejects_module_source_idx on public.sync_rejects(module,source,created_at desc);
alter table public.sync_rejects enable row level security;

-- Nouvelles vues V4.5.1 : noms dédiés pour ne pas casser/renommer les anciennes vues déjà utilisées.
create or replace view public.v_pluviometrie_dashboard_v451 as
select
  o.id,
  o.date_observation,
  s.id as station_id,
  coalesce(s.code_station,o.code_station) as code_site,
  coalesce(s.nom_station,s.village,o.code_station) as nom_site,
  coalesce(s.commune,c.nom) as commune,
  s.latitude,
  s.longitude,
  s.altitude,
  o.pluie_24h_mm as valeur_observee,
  o.pluie_24h_mm,
  o.cumul_mensuel_mm,
  o.observateur,
  o.commentaire,
  o.photo_url,
  o.synced_at,
  case when o.pluie_24h_mm is null or o.pluie_24h_mm < 0 or o.pluie_24h_mm > 300 then true else false end as alerte_valeur,
  case when o.pluie_24h_mm is not null and o.pluie_24h_mm >= 100 then true else false end as alerte_crue,
  false as alerte_secheresse,
  case when s.latitude is null or s.longitude is null then true else false end as alerte_gps,
  case when o.date_observation is null or o.pluie_24h_mm is null then true else false end as alerte_donnee,
  case
    when o.pluie_24h_mm is null then 'Donnée manquante'
    when o.pluie_24h_mm < 0 then 'Valeur négative'
    when o.pluie_24h_mm > 300 then 'Valeur extrême à vérifier'
    when o.pluie_24h_mm >= 100 then 'Pluie exceptionnelle'
    else 'Normal'
  end as statut_qualite,
  case
    when o.pluie_24h_mm is null or o.pluie_24h_mm < 0 or o.pluie_24h_mm > 300 then 'Élevée'
    when o.pluie_24h_mm >= 100 or s.latitude is null or s.longitude is null then 'Moyenne'
    else 'Faible'
  end as niveau_alerte,
  o.source_parent_id
from public.observations_pluvio o
left join public.stations_pluvio s on
     o.station_id=s.id
  or (o.code_station is not null and o.code_station=s.code_station)
  or (o.source_parent_id is not null and o.source_parent_id=s.source_entry_id)
left join public.communes c on s.commune_id=c.id
where o.date_observation is not null and o.pluie_24h_mm is not null;

create or replace view public.v_piezometrie_dashboard_v451 as
select
  o.id,
  o.date_observation,
  p.id as piezometre_id,
  coalesce(p.code_piezo,o.code_piezo) as code_site,
  coalesce(p.localite,p.village,p.code_piezo,o.code_piezo) as nom_site,
  coalesce(p.commune,c.nom) as commune,
  p.village,
  p.localite,
  p.latitude,
  p.longitude,
  o.niveau_statique as valeur_observee,
  o.niveau_statique,
  p.profondeur,
  p.aquifere,
  p.niveau_reference_m,
  p.date_reference,
  case when o.niveau_statique is not null and p.niveau_reference_m is not null then round((o.niveau_statique-p.niveau_reference_m)::numeric,2) else null end as ecart_reference_m,
  case when o.niveau_statique is null or p.niveau_reference_m is null then 'Non comparable'
       when abs(o.niveau_statique-p.niveau_reference_m)<=0.10 then 'Stable'
       when o.niveau_statique>p.niveau_reference_m then 'Baisse' else 'Hausse' end as evolution_reference,
  o.observateur,
  o.commentaire,
  o.photo_url,
  o.synced_at,
  case when o.niveau_statique is null or o.niveau_statique < 0 or (p.profondeur is not null and o.niveau_statique > p.profondeur) then true else false end as alerte_valeur,
  false as alerte_crue,
  case when p.profondeur is not null and o.niveau_statique is not null and o.niveau_statique >= p.profondeur * 0.85 then true else false end as alerte_secheresse,
  case when p.latitude is null or p.longitude is null then true else false end as alerte_gps,
  case when o.date_observation is null or o.niveau_statique is null then true else false end as alerte_donnee,
  case
    when o.niveau_statique is null then 'Donnée manquante'
    when o.niveau_statique < 0 then 'Valeur négative'
    when p.profondeur is not null and o.niveau_statique > p.profondeur then 'Supérieur à la profondeur'
    when p.profondeur is not null and o.niveau_statique >= p.profondeur * 0.85 then 'Niveau critique bas'
    else 'Normal'
  end as statut_qualite,
  case
    when o.niveau_statique is null or o.niveau_statique < 0 or (p.profondeur is not null and o.niveau_statique > p.profondeur) then 'Élevée'
    when p.profondeur is not null and o.niveau_statique is not null and o.niveau_statique >= p.profondeur * 0.85 then 'Moyenne'
    when p.latitude is null or p.longitude is null then 'Moyenne'
    else 'Faible'
  end as niveau_alerte,
  o.source_parent_id
from public.observations_piezo o
left join public.piezometres p on
     o.piezometre_id=p.id
  or (o.code_piezo is not null and o.code_piezo=p.code_piezo)
  or (o.source_parent_id is not null and o.source_parent_id=p.source_entry_id)
left join public.communes c on p.commune_id=c.id
where o.date_observation is not null and o.niveau_statique is not null;

create or replace view public.v_limnimetrie_dashboard_v451 as
select
  o.id,
  o.date_observation,
  s.id as station_id,
  coalesce(s.code_station,o.code_station) as code_site,
  coalesce(s.localite,s.village,s.cours_eau,o.code_station) as nom_site,
  coalesce(s.commune,c.nom) as commune,
  s.latitude,
  s.longitude,
  o.hauteur_eau as valeur_observee,
  o.hauteur_eau,
  o.periode,
  o.observateur,
  o.commentaire,
  o.photo_url,
  o.synced_at,
  case when o.hauteur_eau is null or o.hauteur_eau < 0 or o.hauteur_eau > 2000 then true else false end as alerte_valeur,
  case when o.hauteur_eau is not null and o.hauteur_eau >= 500 then true else false end as alerte_crue,
  case when o.hauteur_eau is not null and o.hauteur_eau <= 5 then true else false end as alerte_secheresse,
  case when s.latitude is null or s.longitude is null then true else false end as alerte_gps,
  case when o.date_observation is null or o.hauteur_eau is null then true else false end as alerte_donnee,
  case
    when o.hauteur_eau is null then 'Donnée manquante'
    when o.hauteur_eau < 0 then 'Valeur négative'
    when o.hauteur_eau > 2000 then 'Valeur extrême à vérifier'
    when o.hauteur_eau >= 500 then 'Niveau haut / crue potentielle'
    when o.hauteur_eau <= 5 then 'Niveau très bas'
    else 'Normal'
  end as statut_qualite,
  case
    when o.hauteur_eau is null or o.hauteur_eau < 0 or o.hauteur_eau > 2000 then 'Élevée'
    when o.hauteur_eau >= 500 or o.hauteur_eau <= 5 or s.latitude is null or s.longitude is null then 'Moyenne'
    else 'Faible'
  end as niveau_alerte,
  o.source_parent_id
from public.observations_limni o
left join public.stations_limni s on
     o.station_id=s.id
  or (o.code_station is not null and o.code_station=s.code_station)
  or (o.source_parent_id is not null and o.source_parent_id=s.source_entry_id)
left join public.communes c on s.commune_id=c.id
where o.date_observation is not null and o.hauteur_eau is not null;

grant select on public.v_pluviometrie_dashboard_v451 to anon, authenticated;
grant select on public.v_piezometrie_dashboard_v451 to anon, authenticated;
grant select on public.v_limnimetrie_dashboard_v451 to anon, authenticated;

delete from public.sync_rejects where created_at < now() - interval '90 days';

commit;
