"use client";
import { useEffect, useMemo, useState } from "react";
import { centroid, countBy, haversineKm, linearTrend, nearbyFeatures, pointInGeometry, polygonsByCentroid, sumBy, type Feature, type FeatureCollection } from "@/lib/decisionnel/geoprocessing";

type Temporal={station:string;date:string;value:number;commune?:string;village?:string;latitude?:number;longitude?:number};
type Datasets={basins:FeatureCollection;subbasins:FeatureCollection;communes:FeatureCollection;restorations:FeatureCollection;piezos:FeatureCollection};
const empty:FeatureCollection={type:"FeatureCollection",features:[]};
const urls={basins:"/data/hydrographie/grand_bassin.geojson",subbasins:"/data/hydrographie/sous_bassins.geojson",communes:"/data/decisionnel/communes_projet_enabel.geojson",restorations:"/data/decisionnel/restaurations.geojson",piezos:"/data/decisionnel/piezometres_ptcs.geojson"};
function pct(v:number){return `${Math.round(v*10)/10}%`;}
function n(v:number,d=1){return new Intl.NumberFormat("fr-FR",{maximumFractionDigits:d}).format(v||0);}
function label(f:Feature,i:number,type:string){const p=f.properties||{};return String(p.commune||p.Nom||p.nom||p.Num_bassin||p.HydroID||p.OBJECTID||`${type} ${i+1}`);}

export default function DecisionSupportDashboard(){
 const [data,setData]=useState<Datasets>({basins:empty,subbasins:empty,communes:empty,restorations:empty,piezos:empty});
 const [temporal,setTemporal]=useState<{observations:Temporal[];pluie:Temporal[];source:string}>({observations:[],pluie:[],source:"Chargement"});
 const [zoneType,setZoneType]=useState<"basins"|"subbasins"|"communes">("subbasins");
 const [zoneIndex,setZoneIndex]=useState(0); const [radius,setRadius]=useState(2); const [scenarioHa,setScenarioHa]=useState(500); const [budget,setBudget]=useState(100000000);
 useEffect(()=>{Promise.all(Object.entries(urls).map(async([k,u])=>[k,await fetch(u).then(r=>r.json())])).then(entries=>setData(Object.fromEntries(entries) as Datasets));fetch("/api/decisionnel/temporal",{cache:"no-store"}).then(r=>r.json()).then(j=>setTemporal({observations:j.observations||[],pluie:j.pluie||[],source:j.source||"Supabase"})).catch(()=>setTemporal({observations:[],pluie:[],source:"Indisponible"}));},[]);
 const zones=data[zoneType].features; const zone=zones[zoneIndex]||zones[0];
 const analysis=useMemo(()=>{
  if(!zone) return null;
  const restorations=polygonsByCentroid(data.restorations.features,zone); const piezos=data.piezos.features.filter(f=>pointInGeometry(f.geometry.coordinates,zone.geometry));
  const surface=sumBy(restorations,f=>Number(f.properties?.surface_ha)); const tech=countBy(restorations,f=>String(f.properties?.technologie||"Non renseigné"));
  const nearby=piezos.map(p=>({piezo:p,nearby:nearbyFeatures(p,restorations,radius)}));
  const covered=nearby.filter(x=>x.nearby.length>0).length; const avgDistance=nearby.flatMap(x=>x.nearby.slice(0,1).map(y=>y.distanceKm));
  const density=surface? piezos.length/(surface/100):0;
  return {restorations,piezos,surface,tech,covered,coverage:piezos.length?covered/piezos.length*100:0,avgDistance:avgDistance.length?avgDistance.reduce((a,b)=>a+b,0)/avgDistance.length:null,density};
 },[zone,data.restorations.features,data.piezos.features,radius]);
 const stationTrends=useMemo(()=>{
  const groups=new Map<string,Temporal[]>(); temporal.observations.forEach(o=>{const k=o.station||`${o.commune}-${o.village}`;if(!groups.has(k))groups.set(k,[]);groups.get(k)!.push(o);});
  return Array.from(groups.entries()).map(([station,values])=>({station,...linearTrend(values.map(v=>({date:v.date,value:v.value}))),values})).sort((a,b)=>(b.count||0)-(a.count||0));
 },[temporal.observations]);
 const scenario=useMemo(()=>{
  if(!analysis) return null; const current=analysis.surface; const target=current+scenarioHa; const monitoringGap=Math.max(0,5-analysis.piezos.length); const unitCost=scenarioHa?budget/scenarioHa:0;
  const rechargePotential=Math.min(100,30+(scenarioHa/Math.max(1,current+scenarioHa))*45+Math.min(25,analysis.coverage/4));
  return {current,target,unitCost,monitoringGap,rechargePotential,priority:rechargePotential>=70?"Élevée":rechargePotential>=50?"Moyenne":"Faible"};
 },[analysis,scenarioHa,budget]);
 const ranked=useMemo(()=>data.subbasins.features.map((z,i)=>{const r=polygonsByCentroid(data.restorations.features,z);const p=data.piezos.features.filter(x=>pointInGeometry(x.geometry.coordinates,z.geometry));const ha=sumBy(r,x=>Number(x.properties?.surface_ha));const score=Math.round(Math.min(100,50*(1-Math.min(1,ha/500))+35*(1-Math.min(1,p.length/3))+15*(r.length===0?1:0)));return {i,label:label(z,i,"Sous-bassin"),ha,piezos:p.length,score};}).sort((a,b)=>b.score-a.score).slice(0,10),[data]);
 if(!zone||!analysis) return <div className="panel">Chargement du moteur SIG décisionnel…</div>;
 return <div className="decisionnel-dashboard">
  <section className="panel decision-hero"><div><span className="eyebrow">PSORE V3.1–V3.5</span><h2>Moteur SIG décisionnel</h2><p>Géotraitements, analyses spatiales et temporelles, mesure d’impact et scénarios de priorisation.</p></div><div className="decision-score"><strong>{Math.round(analysis.coverage)}</strong><span>% des piézomètres proches d’une restauration</span></div></section>
  <section className="panel"><h2>Paramètres d’analyse</h2><div className="decision-filters"><label>Unité territoriale<select value={zoneType} onChange={e=>{setZoneType(e.target.value as any);setZoneIndex(0)}}><option value="basins">Bassin</option><option value="subbasins">Sous-bassin</option><option value="communes">Commune Enabel</option></select></label><label>Zone<select value={zoneIndex} onChange={e=>setZoneIndex(Number(e.target.value))}>{zones.map((f,i)=><option key={i} value={i}>{label(f,i,zoneType)}</option>)}</select></label><label>Rayon d’influence<select value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value={0.1}>100 m</option><option value={0.25}>250 m</option><option value={0.5}>500 m</option><option value={1}>1 km</option><option value={2}>2 km</option><option value={5}>5 km</option><option value={10}>10 km</option></select></label></div></section>
  <section className="decision-kpis"><article><small>Sites restaurés</small><b>{analysis.restorations.length}</b></article><article><small>Surface restaurée</small><b>{n(analysis.surface)} ha</b></article><article><small>Piézomètres</small><b>{analysis.piezos.length}</b></article><article><small>Couverture à {radius} km</small><b>{pct(analysis.coverage)}</b></article><article><small>Distance moyenne minimale</small><b>{analysis.avgDistance===null?"—":`${n(analysis.avgDistance,2)} km`}</b></article><article><small>Technologies</small><b>{Object.keys(analysis.tech).length}</b></article></section>
  <section className="decision-grid"><div className="panel"><h2>Répartition par technologie</h2>{Object.entries(analysis.tech).sort((a,b)=>b[1]-a[1]).map(([k,v])=><div className="decision-bar" key={k}><span>{k}</span><div><i style={{width:`${Math.max(3,v/Math.max(1,analysis.restorations.length)*100)}%`}}/></div><b>{v}</b></div>)}{!analysis.restorations.length&&<p className="muted">Aucune restauration dans cette zone.</p>}</div><div className="panel"><h2>Géotraitements automatiques</h2><div className="process-list"><span>✓ Intersection restaurations × territoire</span><span>✓ Inclusion des piézomètres</span><span>✓ Buffers multi-distances</span><span>✓ Distance minimale restauration–piézomètre</span><span>✓ Agrégation des surfaces et technologies</span><span>✓ Score de couverture du suivi</span></div></div></section>
  <section className="panel"><h2>Analyse temporelle piézométrique</h2><p className="muted">Source : {temporal.source}. La tendance est calculée sur la profondeur à l’eau ; une baisse de la valeur traduit généralement une remontée de la nappe.</p><div className="table-wrap"><table className="table"><thead><tr><th>Station</th><th>Mesures</th><th>Variation</th><th>Pente</th><th>Tendance</th></tr></thead><tbody>{stationTrends.slice(0,20).map(t=><tr key={t.station}><td>{t.station}</td><td>{t.count}</td><td>{t.delta===null?"—":`${n(t.delta,2)} m`}</td><td>{t.slope===null?"—":n(t.slope,3)}</td><td><span className={`trend trend-${t.classification.toLowerCase().replace("é","e")}`}>{t.classification}</span></td></tr>)}</tbody></table></div>{!stationTrends.length&&<p className="quality-warning">Aucune série piézométrique exploitable dans Supabase. Le module est prêt et s’alimentera après synchronisation/import.</p>}</section>
  <section className="decision-grid"><div className="panel"><h2>Scénario d’investissement</h2><div className="scenario-form"><label>Surface additionnelle (ha)<input type="number" min="0" value={scenarioHa} onChange={e=>setScenarioHa(Number(e.target.value))}/></label><label>Budget indicatif (FCFA)<input type="number" min="0" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label></div>{scenario&&<div className="scenario-results"><p><b>Surface projetée :</b> {n(scenario.target)} ha</p><p><b>Coût indicatif :</b> {n(scenario.unitCost,0)} FCFA/ha</p><p><b>Potentiel relatif :</b> {n(scenario.rechargePotential)} /100</p><p><b>Priorité :</b> {scenario.priority}</p><p><b>Déficit de suivi :</b> {scenario.monitoringGap} piézomètre(s) recommandé(s)</p></div>}<small className="muted">Le score est un outil de présélection, non une estimation hydrogéologique de recharge.</small></div><div className="panel"><h2>Sous-bassins prioritaires</h2>{ranked.map((r,i)=><div className="priority-row" key={r.i}><b>{i+1}</b><span>{r.label}<small>{n(r.ha)} ha restaurés · {r.piezos} piézomètre(s)</small></span><strong>{r.score}/100</strong></div>)}</div></section>
  <section className="panel"><h2>Protocole recommandé pour mesurer l’impact</h2><div className="method-grid"><article><b>1. Baseline</b><p>Au moins 12 mois avant intervention lorsque disponible.</p></article><article><b>2. Zones témoins</b><p>Sous-bassins comparables sans restauration.</p></article><article><b>3. Normalisation climatique</b><p>Comparer pluie cumulée, saison et décalage recharge–nappe.</p></article><article><b>4. Comparaison technologique</b><p>Stratifier par technologie, surface, âge et distance.</p></article><article><b>5. Incertitude</b><p>Afficher taille d’échantillon, données manquantes et confiance.</p></article></div></section>
 </div>;
}
