export const dynamic="force-dynamic";
export const revalidate=0;
export const fetchCache="force-no-store";
export const runtime="nodejs";

import {NextRequest,NextResponse} from "next/server";
import {jsPDF} from "jspdf";
import {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,AlignmentType,ShadingType} from "docx";
import {requireApiRole} from "@/lib/auth-server";
import {ROLE_ADMIN,ROLE_DNH,ROLE_SUPER_ADMIN} from "@/lib/permissions";
import {loadHydroRows} from "@/lib/hydro-data";

type M="pluviometrie"|"piezometrie"|"limnimetrie";
const CFG:any={pluviometrie:{v:"pluie_24h_mm",u:"mm",title:"Suivi pluviométrique"},piezometrie:{v:"niveau_statique",u:"m",title:"Suivi piézométrique"},limnimetrie:{v:"hauteur_eau",u:"cm",title:"Suivi limnimétrique"}};
const C={navy:"#0B2545",blue:"#0877B9",cyan:"#37B6D4",green:"#1F9D63",orange:"#D97706",red:"#C2413A",gray:"#5F6F82",light:"#F7FAFC",line:"#D9E5EF"};
const t=(v:any)=>String(v??"").trim(), n=(v:any)=>{if(v===null||v===undefined||v==="")return null;const x=Number(String(v).replace(",","."));return Number.isFinite(x)?x:null}, d=(v:any)=>t(v).slice(0,10), norm=(v:any)=>t(v).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const fmt=(v:any,k=2)=>{const x=n(v);return x===null?"—":x.toLocaleString("fr-FR",{minimumFractionDigits:k,maximumFractionDigits:k})}, signed=(v:any,k=2)=>{const x=n(v);return x===null?"—":`${x>0?"+":""}${fmt(x,k)}`};
const rgb=(h:string):[number,number,number]=>{const x=h.replace("#","");return[parseInt(x.slice(0,2),16),parseInt(x.slice(2,4),16),parseInt(x.slice(4,6),16)]};
const station=(r:any)=>t(r.code_site||r.code_station||r.code_piezo), localite=(r:any)=>t(r.nom_site||r.localite||r.village), hour=(r:any)=>t(r.heure_observation||r.heure||r.time||r.timestamp).slice(0,5);
function filter(rows:any[],sp:URLSearchParams){const list=(k:string)=>norm(sp.get(k)||"").split(",").map(x=>x.trim()).filter(Boolean),cs=list("communes"),ls=list("localites"),ss=list("stations"),start=sp.get("start")||"",end=sp.get("end")||"";return rows.filter(r=>(!cs.length||cs.includes(norm(r.commune)))&&(!ls.length||ls.includes(norm(localite(r))))&&(!ss.length||ss.includes(norm(station(r))))&&(!start||d(r.date_observation)>=start)&&(!end||d(r.date_observation)<=end))}
function usable(rows:any[],m:M){const seen=new Set<string>();return rows.filter(r=>{const v=n(r[CFG[m].v]),key=`${station(r)}|${d(r.date_observation)}|${hour(r)}|${v??""}`,bad=!station(r)||!/^\d{4}-\d{2}-\d{2}$/.test(d(r.date_observation))||v===null||d(r.date_observation)>new Date().toISOString().slice(0,10),dup=seen.has(key);seen.add(key);return !bad&&!dup})}
function trend(rate:number|null){if(rate===null)return{label:"Non calculable",color:C.gray};if(rate>10)return{label:"Remontée marquée",color:C.green};if(rate>5)return{label:"Remontée",color:C.green};if(rate>=-5)return{label:"Relativement stable",color:C.blue};if(rate>=-10)return{label:"Baisse",color:C.orange};return{label:"Baisse marquée",color:C.red}}
function analytics(rows:any[],m:M){const u=usable(rows,m),by=new Map<string,any[]>();for(const r of u){const a=by.get(station(r))||[];a.push(r);by.set(station(r),a)};const st=[...by].map(([code,a])=>{a.sort((x,y)=>(d(x.date_observation)+hour(x)).localeCompare(d(y.date_observation)+hour(y)));const vals=a.map(x=>n(x[CFG[m].v])!).filter(Number.isFinite),first=vals[0]??null,last=vals.at(-1)??null,ev=m==="piezometrie"&&first!==null&&last!==null?first-last:last!==null&&first!==null?last-first:null,rate=ev!==null&&first?ev/first*100:null;return{code,localite:localite(a[0]),commune:t(a[0].commune),lat:n(a[0].latitude),lon:n(a[0].longitude),first,last,mean:vals.length?vals.reduce((s,x)=>s+x,0)/vals.length:null,min:vals.length?Math.min(...vals):null,max:vals.length?Math.max(...vals):null,total:vals.reduce((s,x)=>s+x,0),count:vals.length,evolution:ev,rate,tendance:trend(rate)}});const all=u.map(r=>n(r[CFG[m].v])!).filter(Number.isFinite),avg=all.length?all.reduce((a,b)=>a+b,0)/all.length:null,total=all.reduce((a,b)=>a+b,0),max=all.length?Math.max(...all):null,min=all.length?Math.min(...all):null,rainy=new Set(u.filter(r=>(n(r[CFG[m].v])||0)>=.1).map(r=>d(r.date_observation))).size;return{u,st,avg,total,max,min,rainy}}
function territory(rows:any[],sp:URLSearchParams){const q=sp.get("communes");if(q)return q.split(",").map(x=>x.trim()).join(" + ");const cs=[...new Set(rows.map(r=>t(r.commune)).filter(Boolean))];return cs.length?cs.join(" + "):"Territoire PTCS"}
function period(rows:any[],sp:URLSearchParams){const ds=rows.map(r=>d(r.date_observation)).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)).sort();return `${sp.get("start")||ds[0]||"—"} → ${sp.get("end")||ds.at(-1)||"—"}`}
function card(p:jsPDF,x:number,y:number,w:number,label:string,value:string,color:string){p.setFillColor(255,255,255);p.setDrawColor(...rgb(C.line));p.roundedRect(x,y,w,20,3,3,"FD");p.setFillColor(...rgb(color));p.roundedRect(x,y,3,20,2,2,"F");p.setTextColor(...rgb(C.gray));p.setFontSize(5.5);p.setFont("helvetica","normal");p.text(label,x+6,y+6);p.setTextColor(...rgb(C.navy));p.setFontSize(9);p.setFont("helvetica","bold");p.text(value,x+6,y+15)}
function barChart(p:jsPDF,title:string,items:any[],x:number,y:number,w:number,h:number,unit:string){p.setTextColor(...rgb(C.navy));p.setFont("helvetica","bold");p.setFontSize(7);p.text(title,x,y);const vals=items.map(i=>Math.abs(Number(i.value)||0)),mx=Math.max(...vals,1),base=y+h-7;p.setDrawColor(...rgb(C.line));p.line(x,base,x+w,base);const bw=Math.min(12,(w-8)/Math.max(items.length,1)-2);items.slice(0,12).forEach((it,i)=>{const bh=Math.abs(Number(it.value)||0)/mx*(h-17),xx=x+5+i*((w-10)/Math.max(items.length,1));p.setFillColor(...rgb(it.color||C.blue));p.rect(xx,base-bh,bw,bh,"F");p.setTextColor(...rgb(C.gray));p.setFontSize(4);p.text(String(it.label).slice(0,9),xx,base+4,{angle:25});});p.setFontSize(4);p.text(unit,x+w-12,y)}
async function drawMap(p:jsPDF,st:any[],sp:URLSearchParams,x:number,y:number,w:number,h:number){const pts=st.filter(s=>s.lat!==null&&s.lon!==null&&s.lat>=-90&&s.lat<=90&&s.lon>=-180&&s.lon<=180);p.setFillColor(...rgb(C.light));p.setDrawColor(...rgb(C.line));p.roundedRect(x,y,w,h,2,2,"FD");p.setTextColor(...rgb(C.navy));p.setFont("helvetica","bold");p.setFontSize(7);p.text("Localisation des stations",x,y-3);if(!pts.length){p.setFontSize(5);p.text("Aucune station géolocalisée",x+4,y+10);return}let minLon=Math.min(...pts.map(s=>s.lon)),maxLon=Math.max(...pts.map(s=>s.lon)),minLat=Math.min(...pts.map(s=>s.lat)),maxLat=Math.max(...pts.map(s=>s.lat));const dx=Math.max(maxLon-minLon,.04),dy=Math.max(maxLat-minLat,.04);minLon-=dx*.12;maxLon+=dx*.12;minLat-=dy*.12;maxLat+=dy*.12;const px=(lo:number)=>x+5+(lo-minLon)/(maxLon-minLon)*(w-10),py=(la:number)=>y+h-6-(la-minLat)/(maxLat-minLat)*(h-12);try{const z=9,N=2**z,cLon=(minLon+maxLon)/2,cLat=(minLat+maxLat)/2,tx=Math.floor((cLon+180)/360*N),rad=cLat*Math.PI/180,ty=Math.floor((1-Math.log(Math.tan(rad)+1/Math.cos(rad))/Math.PI)/2*N),sat=(sp.get("basemap")||"")==="satellite",url=sat?`https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${z}/${ty}/${tx}`:`https://tile.openstreetmap.org/${z}/${tx}/${ty}.png`,r=await fetch(url,{headers:{"User-Agent":"PSORE-PTCS/5"}});if(r.ok)p.addImage(new Uint8Array(await r.arrayBuffer()),sat?"JPEG":"PNG",x+1,y+1,w-2,h-2)}catch{}
for(const s of pts){const xx=px(s.lon),yy=py(s.lat);p.setFillColor(...rgb(C.red));p.setDrawColor(255,255,255);p.circle(xx,yy,1.2,"FD");p.setTextColor(...rgb(C.navy));p.setFont("helvetica","bold");p.setFontSize(4.2);p.text(s.code,xx+1.8,yy-1)}p.setFont("helvetica","normal");p.setFontSize(4);p.setTextColor(...rgb(C.gray));p.text(`${pts.length} station(s) géolocalisée(s)`,x+2,y+h-2)}
function headers(m:M){if(m==="piezometrie")return["Station","Localité","Commune","Initial (m)","Final (m)","Évolution (m)","Taux (%)","Tendance","Mesures"];if(m==="pluviometrie")return["Station","Localité","Commune","Cumul (mm)","Moyenne","Maximum","Mesures"];return["Station","Localité","Commune","Moyenne (cm)","Minimum","Maximum","Mesures"]}
function values(s:any,m:M){if(m==="piezometrie")return[s.code,s.localite,s.commune,fmt(s.first),fmt(s.last),signed(s.evolution),signed(s.rate,1),s.tendance.label,String(s.count)];if(m==="pluviometrie")return[s.code,s.localite,s.commune,fmt(s.total,1),fmt(s.mean,1),fmt(s.max,1),String(s.count)];return[s.code,s.localite,s.commune,fmt(s.mean,1),fmt(s.min,1),fmt(s.max,1),String(s.count)]}
function summary(a:any,m:M){if(m==="piezometrie"){const valid=a.st.filter((s:any)=>s.rate!==null),ev=valid.length?valid.reduce((x:any,s:any)=>x+s.evolution,0)/valid.length:null,rate=valid.length?valid.reduce((x:any,s:any)=>x+s.rate,0)/valid.length:null;return{cards:[["Niveau moyen",`${fmt(a.avg)} m`,C.blue],["Évolution moyenne",`${signed(ev)} m`,trend(rate).color],["Taux moyen",`${signed(rate,1)} %`,trend(rate).color],["Stations",String(a.st.length),C.cyan]],text:`L'évolution moyenne du niveau est de ${signed(ev)} m (${signed(rate,1)} %), correspondant à une ${trend(rate).label.toLowerCase()}. La lecture doit être complétée par le détail des stations et leur contexte local.`}}if(m==="pluviometrie")return{cards:[["Pluie moyenne",`${fmt(a.avg,1)} mm`,C.blue],["Cumul",`${fmt(a.total,1)} mm`,C.cyan],["Jours pluvieux",String(a.rainy),C.green],["Maximum",`${fmt(a.max,1)} mm`,C.orange]],text:`La période totalise ${fmt(a.total,1)} mm pour une pluie moyenne observée de ${fmt(a.avg,1)} mm et ${a.rainy} jour(s) pluvieux. Les cumuls par station permettent d'identifier les contrastes spatiaux.`};return{cards:[["Niveau moyen",`${fmt(a.avg,1)} cm`,C.blue],["Minimum",`${fmt(a.min,1)} cm`,C.cyan],["Maximum",`${fmt(a.max,1)} cm`,C.orange],["Stations",String(a.st.length),C.green]],text:`Le niveau moyen observé est de ${fmt(a.avg,1)} cm, avec un minimum de ${fmt(a.min,1)} cm et un maximum de ${fmt(a.max,1)} cm. Le détail par station précise la variabilité spatiale.`}}
async function pdf(a:any,m:M,sp:URLSearchParams,terr:string,per:string){const p=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"}),S=summary(a,m);p.setFillColor(...rgb(C.navy));p.rect(0,0,297,27,"F");p.setTextColor(255,255,255);p.setFont("helvetica","bold");p.setFontSize(15);p.text(`PSORE — ${CFG[m].title}`,12,11);p.setFont("helvetica","normal");p.setFontSize(6.5);p.text(`Territoire : ${terr}  •  Période : ${per}  •  PTCS – Enabel – DNH/DRHK`,12,19);S.cards.forEach((c:any,i:number)=>card(p,12+i*68,34,62,c[0],c[1],c[2]));p.setTextColor(...rgb(C.navy));p.setFont("helvetica","bold");p.setFontSize(8);p.text("À retenir pour la décision",12,64);p.setFont("helvetica","normal");p.setTextColor(...rgb(C.gray));p.setFontSize(6);p.text(p.splitTextToSize(S.text,128),12,72);const chartItems=a.st.map((s:any)=>({label:s.code,value:m==="piezometrie"?s.evolution:m==="pluviometrie"?s.total:s.mean,color:m==="piezometrie"?s.tendance.color:C.blue}));barChart(p,m==="piezometrie"?"Évolution par station":m==="pluviometrie"?"Cumul par station":"Niveau moyen par station",chartItems,12,91,128,58,CFG[m].u);await drawMap(p,a.st,sp,150,66,135,83);p.addPage("a4","landscape");p.setFillColor(...rgb(C.navy));p.rect(0,0,297,20,"F");p.setTextColor(255,255,255);p.setFont("helvetica","bold");p.setFontSize(11);p.text("Détail par station",12,12);const H=headers(m),colW=(273/H.length);p.setFillColor(...rgb(C.blue));p.rect(12,28,273,9,"F");p.setTextColor(255,255,255);p.setFontSize(5);H.forEach((h,i)=>p.text(h,13+i*colW,34));let yy=37;for(const s of a.st){if(yy>194){p.addPage("a4","landscape");yy=20;p.setFillColor(...rgb(C.blue));p.rect(12,yy,273,9,"F");p.setTextColor(255,255,255);H.forEach((h,i)=>p.text(h,13+i*colW,yy+6));yy+=9}const vals=values(s,m);p.setFillColor(...rgb(yy%2?"#FFFFFF":C.light));p.rect(12,yy,273,8,"F");vals.forEach((v,i)=>{p.setTextColor(...rgb(m==="piezometrie"&&i===7?s.tendance.color:C.navy));p.setFont("helvetica",m==="piezometrie"&&i===7?"bold":"normal");p.setFontSize(4.8);p.text(String(v).slice(0,25),13+i*colW,yy+5)});yy+=8}return p.output("arraybuffer")}
function docx(a:any,m:M,terr:string,per:string){const S=summary(a,m),head=headers(m),rows=[new TableRow({children:head.map(h=>new TableCell({shading:{type:ShadingType.CLEAR,fill:"0877B9"},children:[new Paragraph({children:[new TextRun({text:h,bold:true,color:"FFFFFF"})]})]}))}),...a.st.map((s:any)=>new TableRow({children:values(s,m).map((v:string,i:number)=>new TableCell({shading:m==="piezometrie"&&i===7?{type:ShadingType.CLEAR,fill:s.tendance.color.replace("#","")+"22"}:undefined,children:[new Paragraph({children:[new TextRun({text:String(v),bold:m==="piezometrie"&&i===7,color:m==="piezometrie"&&i===7?s.tendance.color.replace("#",""):"0B2545"})]})]}))}))];const children:any[]=[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:`PSORE — ${CFG[m].title}`,bold:true,size:32,color:"0B2545"})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:`PTCS – Enabel – DNH/DRHK  |  ${terr}  |  ${per}`,color:"5F6F82"})]}),new Paragraph({children:[new TextRun({text:"Indicateurs clés",bold:true,size:24,color:"0877B9"})]}),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:S.cards.map((c:any)=>new TableCell({shading:{type:ShadingType.CLEAR,fill:"F7FAFC"},children:[new Paragraph({children:[new TextRun({text:c[0],color:"5F6F82"})]}),new Paragraph({children:[new TextRun({text:c[1],bold:true,size:26,color:c[2].replace("#","")})]})]}))})]}),new Paragraph({children:[new TextRun({text:"À retenir pour la décision",bold:true,size:24,color:"0877B9"})]}),new Paragraph(S.text),new Paragraph({children:[new TextRun({text:"Détail par station",bold:true,size:24,color:"0877B9"})]}),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows})];return Packer.toBuffer(new Document({sections:[{children}]}))}
export async function GET(req:NextRequest){const auth=await requireApiRole(req,[ROLE_DNH,ROLE_ADMIN,ROLE_SUPER_ADMIN]);if("response" in auth)return auth.response;const sp=req.nextUrl.searchParams,m=sp.get("module") as M,format=(sp.get("format")||"pdf").toLowerCase();if(!CFG[m]||!["pdf","docx"].includes(format))return NextResponse.json({error:"Module ou format non supporté"},{status:400});try{const loaded:any=await loadHydroRows(m),rows=filter(loaded.rows||[],sp),a=analytics(rows,m),terr=territory(rows,sp),per=period(rows,sp);if(!a.u.length)return NextResponse.json({error:"Aucune donnée exploitable pour les filtres sélectionnés."},{status:404});const body=format==="pdf"?await pdf(a,m,sp,terr,per):await docx(a,m,terr,per);return new NextResponse(body as any,{headers:{"Content-Type":format==="pdf"?"application/pdf":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","Content-Disposition":`attachment; filename="PSORE_${m}_V5.${format}"`,"Cache-Control":"no-store"}})}catch(e:any){return NextResponse.json({error:e?.message||"Erreur de génération V5"},{status:500})}}
