export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {authorizeSync} from "../_auth";
import {getActiveEpicollectSources,withChildParentRef,formRefFromApiUrl} from "@/services/epicollect/sources";
import {hasSupabaseAdminEnv,getSupabaseAdminEnvStatus,supabaseAdmin} from "@/lib/supabase-admin";

const TARGETS:Record<string,{table:string;value?:string}>={"pluviometrie:stations":{table:"stations_pluvio"},"pluviometrie:releves":{table:"observations_pluvio",value:"pluie_24h_mm"},"piezometrie:referentiel":{table:"piezometres"},"piezometrie:mesures":{table:"observations_piezo",value:"niveau_statique"},"limnimetrie:stations":{table:"stations_limni"},"limnimetrie:lectures":{table:"observations_limni",value:"hauteur_eau"},"points_eau:inventaire":{table:"points_eau"}};
async function countRows(table:string,value?:string){try{let q=supabaseAdmin.from(table).select("id",{count:"exact",head:true});if(value)q=q.not(value,"is",null);const{count,error}=await q;return error?{count:null,error:error.message}:{count:Number(count||0),error:null};}catch(e:any){return{count:null,error:e?.message||String(e)}}}
async function probeApi(apiUrl:string){try{const u=new URL(apiUrl);u.searchParams.set("per_page","1");u.searchParams.set("page","1");const r=await fetch(u.toString(),{cache:"no-store",headers:{Accept:"application/json","User-Agent":"PSORE-Diagnostic/4.6.0"}});const text=await r.text();if(!r.ok)return{ok:false,status:r.status,error:text.slice(0,300)};const j=JSON.parse(text);const meta=j?.meta||j?.data?.meta||{};const entries=j?.data?.entries||j?.entries||[];return{ok:true,status:r.status,total:Number.isFinite(Number(meta.total))?Number(meta.total):null,sample_keys:Array.isArray(entries)&&entries[0]?Object.keys(entries[0]).slice(0,30):[]};}catch(e:any){return{ok:false,status:null,error:e?.message||String(e)}}}
export async function GET(req:NextRequest){const auth=await authorizeSync(req);if(!auth.ok)return auth.response;const shouldProbe=req.nextUrl.searchParams.get("probe")==="1";const raw=await getActiveEpicollectSources();const out=[] as any[];for(const s of raw){const moduleSources=raw.filter(x=>x.module===s.module);const effective=withChildParentRef(s,moduleSources);const t=TARGETS[`${s.module}:${s.type_source}`];const c=t?await countRows(t.table,t.value):{count:null,error:"cible inconnue"};const probe=shouldProbe?await probeApi(effective.api_url):null;out.push({module:s.module,type_source:s.type_source,libelle:s.libelle,project_slug:s.project_slug,form_ref:formRefFromApiUrl(s.api_url),parent_form_ref:new URL(effective.api_url).searchParams.get("parent_form_ref"),branch_ref:new URL(effective.api_url).searchParams.get("branch_ref"),effective_api_url:effective.api_url,table:t?.table||null,donnees_exploitables:c.count,db_error:c.error,probe});}return NextResponse.json({ok:true,mode:auth.mode,engine:"v4.7.0",supabase:hasSupabaseAdminEnv(),environment:getSupabaseAdminEnvStatus(),cronSecretConfigured:Boolean(process.env.CRON_SECRET||process.env.SYNC_SECRET),sources:out});}
