export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {authorizeSync} from "../_auth";
import {getActiveEpicollectSources,withChildParentRef,formRefFromApiUrl} from "@/services/epicollect/sources";
import {hasSupabaseAdminEnv,getSupabaseAdminEnvStatus,supabaseAdmin} from "@/lib/supabase-admin";

const TARGETS:Record<string,{table:string;value?:string}>={"pluviometrie:stations":{table:"stations_pluvio"},"pluviometrie:releves":{table:"observations_pluvio",value:"pluie_24h_mm"},"piezometrie:referentiel":{table:"piezometres"},"piezometrie:mesures":{table:"observations_piezo",value:"niveau_statique"},"limnimetrie:stations":{table:"stations_limni"},"limnimetrie:lectures":{table:"observations_limni",value:"hauteur_eau"},"points_eau:inventaire":{table:"points_eau"}};
async function countRows(table:string,value?:string){try{let q=supabaseAdmin.from(table).select("id",{count:"exact",head:true});if(value)q=q.not(value,"is",null);const{count,error}=await q;return error?{count:null,error:error.message}:{count:Number(count||0),error:null};}catch(e:any){return{count:null,error:e?.message||String(e)}}}

async function linkedParentStats(table:string){
  const cfg:any={observations_pluvio:["stations_pluvio","source_parent_id"],observations_piezo:["piezometres","source_parent_id"],observations_limni:["stations_limni","source_parent_id"]}[table];
  if(!cfg)return null;
  try{
    const [{data:obs,error:oe},{data:parents,error:pe}]=await Promise.all([supabaseAdmin.from(table).select("source_parent_id").limit(50000),supabaseAdmin.from(cfg[0]).select("source_entry_id").limit(10000)]);
    if(oe||pe)return{total:null,linked:null,unresolved:null,error:oe?.message||pe?.message};
    const ids=new Set((parents||[]).map((x:any)=>String(x.source_entry_id||"")).filter(Boolean));
    const total=(obs||[]).length,linked=(obs||[]).filter((x:any)=>ids.has(String(x.source_parent_id||""))).length;
    return{total,linked,unresolved:total-linked,error:null};
  }catch(e:any){return{total:null,linked:null,unresolved:null,error:e?.message||String(e)}}
}
async function registryStats(module:string,table:string){try{const [{count:registryCount,error:re},{data:obs,error:oe}]=await Promise.all([supabaseAdmin.from("epicollect_parent_registry").select("source_parent_id",{count:"exact",head:true}).eq("module",module),table.startsWith("observations_")?supabaseAdmin.from(table).select("source_parent_id").limit(50000):Promise.resolve({data:[],error:null} as any)]);if(re)return{parents_registre:null,enfants_lies_registre:null,error:re.message};if(oe)return{parents_registre:Number(registryCount||0),enfants_lies_registre:null,error:oe.message};const ids=(obs||[]).map((x:any)=>String(x.source_parent_id||"")).filter(Boolean);if(!ids.length)return{parents_registre:Number(registryCount||0),enfants_lies_registre:0,error:null};const{data:regs,error:rge}=await supabaseAdmin.from("epicollect_parent_registry").select("source_parent_id").eq("module",module).in("source_parent_id",Array.from(new Set(ids)));if(rge)return{parents_registre:Number(registryCount||0),enfants_lies_registre:null,error:rge.message};const set=new Set((regs||[]).map((x:any)=>String(x.source_parent_id||"")));return{parents_registre:Number(registryCount||0),enfants_lies_registre:ids.filter((id:string)=>set.has(id)).length,error:null};}catch(e:any){return{parents_registre:null,enfants_lies_registre:null,error:e?.message||String(e)}}}
async function probeApi(apiUrl:string){try{const u=new URL(apiUrl);u.searchParams.set("per_page","1");u.searchParams.set("page","1");const r=await fetch(u.toString(),{cache:"no-store",headers:{Accept:"application/json","User-Agent":"PSORE-Diagnostic/5.2.1"}});const text=await r.text();if(!r.ok)return{ok:false,status:r.status,error:text.slice(0,300)};const j=JSON.parse(text);const meta=j?.meta||j?.data?.meta||{};const entries=j?.data?.entries||j?.entries||[];return{ok:true,status:r.status,total:Number.isFinite(Number(meta.total))?Number(meta.total):null,sample_keys:Array.isArray(entries)&&entries[0]?Object.keys(entries[0]).slice(0,30):[]};}catch(e:any){return{ok:false,status:null,error:e?.message||String(e)}}}
export async function GET(req:NextRequest){const auth=await authorizeSync(req);if(!auth.ok)return auth.response;const shouldProbe=req.nextUrl.searchParams.get("probe")==="1";const raw=await getActiveEpicollectSources();const out=[] as any[];for(const s of raw){const moduleSources=raw.filter(x=>x.module===s.module);const effective=withChildParentRef(s,moduleSources);const t=TARGETS[`${s.module}:${s.type_source}`];const c=t?await countRows(t.table,t.value):{count:null,error:"cible inconnue"};const relation=t?await linkedParentStats(t.table):null;const registry=t?await registryStats(s.module,t.table):null;const probe=shouldProbe?await probeApi(effective.api_url):null;out.push({module:s.module,type_source:s.type_source,libelle:s.libelle,project_slug:s.project_slug,form_ref:formRefFromApiUrl(s.api_url),parent_form_ref:new URL(effective.api_url).searchParams.get("parent_form_ref"),branch_ref:new URL(effective.api_url).searchParams.get("branch_ref"),effective_api_url:effective.api_url,table:t?.table||null,donnees_exploitables:c.count,relation_parent_enfant:relation,registre_parent:registry,db_error:c.error,probe});}return NextResponse.json({ok:true,mode:auth.mode,engine:"v5.2.1",supabase:hasSupabaseAdminEnv(),environment:getSupabaseAdminEnvStatus(),cronSecretConfigured:Boolean(process.env.CRON_SECRET||process.env.SYNC_SECRET),sources:out});}
