export const dynamic = "force-dynamic";
export const revalidate = 0;
export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import { Document, HeadingLevel, Packer, Paragraph } from "docx";
import * as XLSX from "xlsx";
import { jsPDF } from "jspdf";
import { requireApiRole } from "@/lib/auth-server";
import { ROLE_ADMIN, ROLE_DNH, ROLE_SUPER_ADMIN } from "@/lib/permissions";
import { applyPointEauFilters, readPointEauRows, type PointEauRow } from "@/services/points-eau/analytics";

const t=(v:any)=>String(v??"").trim();
const n=(v:any)=>{const x=Number(String(v??"").replace(",","."));return Number.isFinite(x)?x:null};
const date=(v:any)=>t(v).slice(0,10);
function status(r:PointEauRow){if(r.alerte_gps||r.alerte_ph_donnee)return "Rejetée";if(r.alerte_qualite_eau||r.alerte_photo)return "À vérifier";return "Validée";}
function latestByPoint(rows:PointEauRow[]){const m=new Map<string,PointEauRow>();for(const r of rows){const k=t(r.code_pe)||t(r.source_entry_id)||t(r.id);const p=m.get(k);if(!p||date(r.date_collecte)>date(p.date_collecte))m.set(k,r)}return [...m.values()]}
function exportRows(rows:PointEauRow[]){return rows.map(r=>({Code:r.code_pe,Village:r.village,Commune:r.commune,"Date collecte / mise à jour":date(r.date_collecte),Type:r.type_infrastructure,Fonctionnalité:r.statut_fonctionnalite,Équipement:r.equipement,"Organe de gestion":r.organe_gestion,pH:r.ph,"Température (°C)":r.temperature_c,Conductivité:r.conductivite,TDS:r.tds,"Besoin réhabilitation":r.besoin_rehabilitation,Priorité:r.priorite_rehabilitation,Score:r.score_priorite,Latitude:r.latitude,Longitude:r.longitude,"Statut qualité":status(r)}))}
function csv(rows:any[]){if(!rows.length)return "Aucune donnée\n";const h=Object.keys(rows[0]);const q=(v:any)=>`"${String(v??"").replace(/"/g,'""')}"`;return [h.map(q).join(";"),...rows.map(r=>h.map(k=>q(r[k])).join(";"))].join("\n")}
function rgb(h:string):[number,number,number]{const x=h.replace("#","");return[parseInt(x.slice(0,2),16),parseInt(x.slice(2,4),16),parseInt(x.slice(4,6),16)]}
function makePdf(rows:PointEauRow[],source:string){const p=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});const total=rows.length,verify=rows.filter(r=>status(r)==="À vérifier").length,rejected=rows.filter(r=>status(r)==="Rejetée").length,gps=rows.filter(r=>!r.alerte_gps).length,communes=new Map<string,number>();for(const r of rows){const c=t(r.commune)||"Non renseigné";communes.set(c,(communes.get(c)||0)+1)}p.setFillColor(...rgb("#0B2545"));p.rect(0,0,297,27,"F");p.setTextColor(255,255,255);p.setFont("helvetica","bold");p.setFontSize(15);p.text("PSORE — Inventaire des points d’eau",12,11);p.setFont("helvetica","normal");p.setFontSize(6.5);p.text("Inventaire global des ouvrages — aucune interprétation comme série temporelle",12,19);const cards=[["Points d’eau",total],["Avec GPS",gps],["À vérifier",verify],["Rejetées",rejected],["Communes",new Set(rows.map(r=>t(r.commune)||"Non renseigné")).size]];cards.forEach(([label,value],i)=>{const x=12+i*54;p.setFillColor(255,255,255);p.setDrawColor(217,229,239);p.roundedRect(x,33,50,21,3,3,"FD");p.setTextColor(95,111,130);p.setFontSize(6);p.text(String(label),x+5,40);p.setTextColor(11,37,69);p.setFont("helvetica","bold");p.setFontSize(11);p.text(String(value),x+5,49);p.setFont("helvetica","normal")});p.setTextColor(11,37,69);p.setFont("helvetica","bold");p.setFontSize(8);p.text("Répartition par commune",12,66);p.setFont("helvetica","normal");p.setFontSize(5.5);let y=74;for(const [c,v] of [...communes.entries()].sort((a,b)=>b[1]-a[1]).slice(0,20)){p.text(`${c}: ${v}`,12,y);y+=6;if(y>150)break}p.setFont("helvetica","bold");p.setFontSize(8);p.text("Contrôle qualité",155,66);p.setFont("helvetica","normal");p.setFontSize(6);p.text("Validée : aucune incohérence certaine détectée.",155,76);p.text("À vérifier : alerte qualité, photo manquante ou plausibilité.",155,85);p.text("Rejetée : GPS manquant/invalide ou donnée physiquement invalide.",155,94);p.text(`Source : ${source}`,155,105);p.text("Le point d’eau est une fiche d’inventaire pouvant être mise à jour périodiquement.",155,116);p.text("Il n’est pas traité comme une station à observations quotidiennes.",155,125);p.setTextColor(95,111,130);p.setFontSize(4.5);p.text(`PSORE • Inventaire des points d’eau • ${new Date().toISOString().slice(0,10)}`,12,204);p.text("Page 1/1",270,204);return p.output("arraybuffer")}
function makeDocx(rows:PointEauRow[],source:string){const children:Paragraph[]=[new Paragraph({text:"PSORE — Inventaire des points d’eau",heading:HeadingLevel.TITLE}),new Paragraph(`Source : ${source}`),new Paragraph(`Ouvrages : ${rows.length} · Validées : ${rows.filter(r=>status(r)==="Validée").length} · À vérifier : ${rows.filter(r=>status(r)==="À vérifier").length} · Rejetées : ${rows.filter(r=>status(r)==="Rejetée").length}.`),new Paragraph({text:"Principe",heading:HeadingLevel.HEADING_1}),new Paragraph("Le point d’eau est une fiche d’inventaire global, éventuellement mise à jour lors de visites. Il n’est pas traité comme une station possédant une série temporelle quotidienne."),new Paragraph({text:"Qualité",heading:HeadingLevel.HEADING_1}),new Paragraph("Les données sources restent conservées avec leur statut qualité. Les incohérences certaines sont exclues des indicateurs analytiques."),new Paragraph({text:"Répartition communale",heading:HeadingLevel.HEADING_1})];const m=new Map<string,number>();for(const r of rows){const c=t(r.commune)||"Non renseigné";m.set(c,(m.get(c)||0)+1)}for(const [c,v] of m)children.push(new Paragraph(`• ${c} : ${v} point(s) d’eau`));return Packer.toBuffer(new Document({sections:[{children}]}))}
export async function GET(req:NextRequest){const auth=await requireApiRole(req,[ROLE_DNH,ROLE_ADMIN,ROLE_SUPER_ADMIN]);if("response"in auth)return auth.response;const sp=req.nextUrl.searchParams,format=(sp.get("format")||"pdf").toLowerCase(),scope=(sp.get("scope")||"analytic").toLowerCase();try{const loaded=await readPointEauRows();let rows=applyPointEauFilters(loaded.rows,sp);const start=sp.get("start")||"",end=sp.get("end")||"";if(start)rows=rows.filter(r=>date(r.date_collecte)>=start);if(end)rows=rows.filter(r=>date(r.date_collecte)<=end);const sourceRows=rows,analyticRows=latestByPoint(rows).filter(r=>status(r)!=="Rejetée"),chosen=scope==="source"?sourceRows:analyticRows;if(format==="csv")return new Response(csv(exportRows(chosen)),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="psore_points-eau_${scope}.csv"`}});if(format==="xlsx"){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Source:loaded.source,Enregistrements_source:sourceRows.length,Points_analytiques:analyticRows.length,Validees:analyticRows.filter(r=>status(r)==="Validée").length,A_verifier:analyticRows.filter(r=>status(r)==="À vérifier").length}]),"Synthèse");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(exportRows(chosen)),scope==="source"?"Source + qualité":"Inventaire analytique");return new Response(XLSX.write(wb,{type:"array",bookType:"xlsx"}),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="psore_points-eau_${scope}.xlsx"`}})}if(scope==="source")return NextResponse.json({ok:false,error:"Pour l'inventaire source, utilisez CSV ou XLSX."},{status:400});if(format==="docx")return new Response(new Uint8Array(await makeDocx(analyticRows,loaded.source)),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","Content-Disposition":"attachment; filename=\"psore_points-eau_rapport.docx\""}});return new Response(makePdf(analyticRows,loaded.source),{headers:{"Content-Type":"application/pdf","Content-Disposition":"attachment; filename=\"psore_points-eau_rapport.pdf\""}})}catch(e:any){console.error("PSORE points-eau export",e);return NextResponse.json({ok:false,error:e?.message||"Génération du rapport impossible"},{status:500})}}