import fs from 'node:fs';
const must = p => { if (!fs.existsSync(p)) throw new Error(`Fichier manquant: ${p}`); return fs.readFileSync(p,'utf8'); };
const pkg=JSON.parse(must('package.json'));
if(pkg.version!=='5.1.0') throw new Error(`Version package inattendue: ${pkg.version}`);
const registry=must('lib/network-registry.ts');
const count=(section,next)=>{const s=registry.split(`${section}: [`)[1]?.split(`${next}: [`)[0]||'';return (s.match(/\{code:/g)||[]).length};
const pl=count('pluviometrie','piezometrie'), pz=count('piezometrie','limnimetrie');
const li=((registry.split('limnimetrie: [')[1]||'').split('],\n};')[0].match(/\{code:/g)||[]).length;
if(pl!==10||pz!==20||li!==10) throw new Error(`Réseaux officiels incorrects: pluie=${pl}, PZ=${pz}, limni=${li}`);
const map=must('components/map/LeafletMap.tsx');
if(!map.includes('points_eau: false')||!map.includes('piezometrie: false')||!map.includes('pluviometrie: false')||!map.includes('limnimetrie: false')) throw new Error('Les couches ponctuelles ne sont pas toutes désactivées par défaut.');
const protectedActions=must('components/auth/ProtectedActions.tsx');
if(/href=\{`\/api\/reports\/export/.test(protectedActions)) throw new Error('Export rapports encore ouvert par lien direct.');
if(!protectedActions.includes('downloadAuthenticated')) throw new Error('Téléchargement authentifié absent.');
const mod=must('app/api/dashboard/module/route.ts');
if(!mod.includes('NETWORK_STATIONS')||!mod.includes('non_exploitables')) throw new Error('Filtres référentiels / compteur non exploitable absents.');
const report=must('app/api/reports/export/route.ts');
for(const marker of ['loadHydroRows','stationMetaByCode','drawSubBasinExcerpt','Répartition communale','Technologies de restauration']) if(!report.includes(marker)) throw new Error(`Rapports incomplets: ${marker}`);
const dash=must('services/dashboard/institutionnel.ts');
if(!dash.includes('networkTotal(module)')||!dash.includes('distinctOfficialSites')) throw new Error('Dashboard institutionnel ne sépare pas réseau et observations.');
const hydro=must('lib/hydro-data.ts');
if(!hydro.includes('stationMetaByCode')||!hydro.includes('source_parent_id')) throw new Error('Rapprochement station/mesure non strict.');
console.log('PSORE V5.1.0 — vérifications fonctionnelles statiques OK');
console.log(`Réseaux: pluie=${pl}, piezo=${pz}, limni=${li}`);
